window.DEFAULT_ARTICLE_CATALOG = [
    "Ahr Spätburgunder Blanc de Noir halbtrocken weiß, Flasche, 0,75 l",
    "Ahr Spätburgunder Rosé halbtrocken rosé, Flasche, 0,75 l",
    "Moselland Akzente Riesling QbA halbtrocken/weiß, Flasche, 0,75 l",
    "Mosel Akzente Elbling QbA trocken weiß, Flasche, 0,75 l",
    "Himmlisches Tröpfchen Tafelwein weiß, Flasche, 1,00 l",
    "Mosel Paulinshof Winzerriesling trocken weiß, Flasche, 0,75 l",
    "Mosel Van vol.xem Virtuos Riesling trocken weiß, Flasche, 0,75 l",
    "Rheinhessen Eberbach Riesling trocken weiß, Flasche, 0,75 l",
    "Rheinhessen Eberbach Rosé trocken rosé, Flasche, 0,75 l",
    "Rheinhessen Bree Fruity Weisswein süß \u0026 fruchtig, Flasche, 0,75 l",
    "Rheinhessen Bree Fruity Roséwein süß \u0026 fruchtig, Flasche, 0,75 l",
    "Rheinhessen Bree Pinot Noir Spätburgunder QbA rosé, Flasche, 0,75 l",
    "Rheinhessen Dr. Zensen Dornfelder, Flasche, 0,75 l",
    "Rheinhessen Dr. Zenzen Kerner QbA trocken weiß, Flasche, 1,00 l",
    "Rheinhessen Dr. Zenzen Müller Thurgau QbA trocken weiß, Flasche, 1,00 l",
    "Rheinhessen Maybach Grauer Burgunder Rivaner trocken weiß, Flasche, 0,75 l",
    "Rheinhessen Rotkäppchen Grauburgunder trocken weiß, Flasche, 0,75 l",
    "Rheinhessen Rotkäppchen Merlot Regent trocken rot, Flasche, 0,75 l",
    "Rheinhessen Rotkäppchen Weinzeit lieblich weiß, Flasche, 0,75 l",
    "Rheinhessen Rotkäppchen Riesling QbA trocken, Flasche, 0,75 l",
    "Rheinhessen Rotkäppchen Müller-Thurgau QbA, Flasche, 0,75 l",
    "Rheinhessen Rotwild Dornfelder QbA lieblich rosé, Flasche, 0,75 l",
    "Bio Silvaner QbA weiß, Flasche, 0,75 l",
    "Liebfraumilch Cuvée QbA weiß, Flasche, 0,75 l",
    "Bio Dornfelder Vegan QbA rot, Flasche, 0,75 l",
    "Erben Spätlese Cuvée weiß, Flasche, 0,75 l",
    "Rheinhessen Maybach Riesling QbA trocken weiß, Flasche, 0,75 l",
    "Rheinhessen Maybach Sauvignon QbA halbtrocken weiß, Flasche, 0,75 l",
    "Pfalz Dornfelder Landwein Box, Box, 3,00 l",
    "Pfalz Hohenstaufer Pfälzer Landwein halbtrocken weiß, Flasche, 1,00 l",
    "Pfalz Kirschgarten Rosé Dornfelder lieblich rosé, Flasche, 0,75 l",
    "Pfalz Lavendelmeer Blanc feinherb weiß, Flasche, 0,75 l",
    "Pfalz Müller Thurgau Wein Box weiß, Box, 3,00 l",
    "Pfalz Peter \u0026 Peter Grauer Burgunder trocken weiß, Flasche, 0,75 l",
    "Pfalz Peter \u0026 Peter Weißer Burgunder trocken weiß, Flasche, 0,75 l",
    "BioRebe Riesling Vegan QbA halbtrocken weiß, Flasche, 0,75 l",
    "Pfalz Creation Grauer Burgunder, Flasche, 0,75 l",
    "Pfalz Creation Riesling Qualitätswein trocken, Flasche, 0,75 l",
    "Pfalz Creation Spätburgunder, Flasche, 0,75 l",
    "Pfalz Dürkheimer Fronhof Riesling, Flasche, 1,00 l",
    "Pfalz Exclusiv Dornfelder Rotwein QbA trocken, Flasche, 0,75 l",
    "Pfalz Hohenstaufer Dornfelder Qualitätswein lieblich rot, Flasche, 1,00 l",
    "Pfalz Hohenstaufer Kerner QbA weiß, Flasche, 1,00 l",
    "Pfalz Hohenstaufer Müller-Thurgau QbA mild weiß, Flasche, 1,00 l",
    "Pfalz Hohenstaufer Portugieser Rosé QbA mild rosé, Flasche, 1,00 l",
    "Pfalz Hohenstaufer Riesling QbA trocken weiß, Flasche, 1,00 l",
    "Pfalz Hohenstaufer Silvaner QbA halbtrocken weiß, Flasche, 1,00 l",
    "Pfalz Hohenstaufer Spätburgunder QbA trocken rot, Flasche, 1,00 l",
    "Pfalz Kallstadt Kobnert, Flasche, 1,00 l",
    "Pfalz Lorch Portugieser Weißherbst QbA rosé lieblich, Flasche, 1,00 l",
    "Rotkäppchen Dornfelder QbA halbtrocken rot, Flasche, 0,75 l",
    "Pfalz Wegner Rosé QbA feinherb rosé, Flasche, 0,75 l",
    "Pfalz Wegner Grauburgunder QbA trocken weiß, Flasche, 0,75 l",
    "Pfalz Wegner Dornfelder QbA trocken rot, Flasche, 0,75 l",
    "Rotkäppchen Spätburgunder QbA rot, Flasche, 0,75 l",
    "Pfalz Wegner Riesling QbA trocken weiß, Flasche, 0,75 l",
    "Pfalz Wegner Rivaner QbA lieblich weiß, Flasche, 0,75 l",
    "Pfalz Wegner Rosé QbA halbtrocken rosé, Flasche, 0,75 l",
    "Pfalz Wegner Weißburgunder QbA trocken weiß, Flasche, 0,75 l",
    "Pfalz Weinmacher Deidesheimer Hofstück Müller-Thurgau QbA, Flasche, 1,00 l",
    "Pfalz Bree Riesling Qualitätswein feinherb weiß, Flasche, 0,75 l",
    "Pfalz / Rheinhessen Rotwild Dornfelder QbA halbtrocken rot, Flasche, 0,75 l",
    "Pfalz / Rheinhessen Rotwild Dornfelder QbA lieblich rot, Flasche, 0,75 l",
    "Pfalz / Rheinhessen Rotwild Dornfelder QbA trocken rot, Flasche, 0,75 l",
    "Turmfalke Dornfelder Rotwein QbA trocken, Flasche, 0,75 l",
    "Turmfalke Dornfelder Rotwein QbA halbtrocken, Flasche, 0,75 l",
    "Turmfalke Dornfelder Rotwein QbA lieblich, Flasche, 0,75 l",
    "Die Jungen Franken Rotling halbtrocken rosé, Flasche, 0,75 l",
    "Die Jungen Franken QbA weiß, Flasche, 0,75 l",
    "Franken Frisch \u0026 Fruchtig QbA trocken rot, Flasche, 0,75 l",
    "Volkacher Kirchberg Silvaner QbA weiß, Flasche, 0,75 l",
    "Franken Volkacher Kirchberg QbA weiß, Flasche, 1,00 l",
    "Franken Volkacher Kirchberg MTH QbA weiß, Flasche, 1,00 l",
    "Franken Stahl Edelstahl Scheurebe trocken weiß, Flasche, 0,75 l",
    "Franken Volkacher Kirchberg Domina Prädikatswein trocken, Flasche, 0,75 l",
    "Franken Volkacher Kirchberg weiß, Flasche, 1,00 l",
    "Württemberg Fünfklang Dornfelder QbA fruchtig \u0026 süß, Flasche, 0,75 l",
    "Fünfklang Lemberger QbA rosé, Flasche, 0,75 l",
    "Fünfklang Lemberger \u0026 Trollinger QbA rot, Flasche, 0,75 l",
    "Fünfklang Lemberger QbA rot, Flasche, 0,75 l",
    "Württemberg Fünfklang fruchtig \u0026 süss Riesling QbA süß weiß, Flasche, 0,75 l",
    "Fünfklang Riesling QbA weiß, Flasche, 0,75 l",
    "Fünfklang Trollinger QbA rot, Flasche, 0,75 l",
    "Württemberg Fünfklang Weißburgunder QbA trocken weiß, Flasche, 0,75 l",
    "Württemberg Grauburgunder \"G\" QbA trocken weiß, Flasche, 0,75 l",
    "Württemberg Heilbronner Staufenberg Riesling QbA trocken, Flasche, 1,00 l",
    "Württemberg Haberschlachter Heuchelberg Trollinger und Lemberger QbA halbtrocken rot, Flasche, 0,75 l",
    "Württemberg Korber Kopf Trollinger QbA halbtrocken rot, Flasche, 1,00 l",
    "Württemberg Lauffener Katzenbeißer Samtrot QbA, Flasche, 0,75 l",
    "Württemberg Lauffener Kirchenweinberg Schwarzriesling QbA, Flasche, 1,00 l",
    "Württemberg Lauffener Katzenbeißer Schwarzriesling- Weißherbst, Flasche, 1,00 l",
    "Württemberg Lauffener Weingärtner Riesling QbA halbtrocken weiß, Flasche, 1,00 l",
    "Württemberg Lauffener Weingärtner Rotwein Cuvée QbA, Flasche, 1,00 l",
    "Württemberg Lemberger \"L\" QbA trocken rot, Flasche, 0,75 l",
    "Ochsenbacher Stromberg Troll./ Lemberger Qualitätswein, Flasche, 1,00 l",
    "Württemberg Schwäbischer Landwein Cuvée halbtrocken rot, Flasche, 1,00 l",
    "Württemberg Spätburgunder Weißherbst QbA halbtrocken rosé, Flasche, 1,00 l",
    "Württemberg Schillerwein Cuvée QbA halbtrocken rosé, Flasche, 1,00 l",
    "Württemberg Stettener Wartbühl Riesling QbA halbtrocken weiß, Flasche, 1,00 l",
    "Württemberg Stoffel Müller-Thurgau QbA halbtrocken weiß, Flasche, 1,00 l",
    "Württemberg Süß \u0026 Fruchtig Riesling QbA süß weiß, Flasche, 0,75 l",
    "Württemberg Süß \u0026 Fruchtig Trollinger QbA süß rosé, Flasche, 0,75 l",
    "Württemberg Süß \u0026 Fruchtig Samtrot QbA süß rot, Flasche, 0,75 l",
    "Württemberg Trollinger mit Lemberger QbA halbtrocken rot, Flasche, 1,00 l",
    "Trollinger WZG Württemberg QbA rot, Flasche, 0,75 l",
    "Württemberg Zweigelt Rosé QbA fruchtig rosé, Flasche, 0,75 l",
    "Baden 1112 Blanc de Blancs Chardonnay trocken weiß, Flasche, 0,75 l",
    "Baden 1112 Blanc de Noirs trocken weiß, Flasche, 0,75 l",
    "Baden 1112 Grauburgunder trocken weiß, Flasche, 0,75 l",
    "Baden 1112 Gutedel \u0026 Grauburgunder trocken weiß, Flasche, 0,75 l",
    "Baden 1112 Spätburgunder Rosé trocken, Flasche, 0,75 l",
    "Baden 1112 Spätburgunder trocken rot, Flasche, 0,75 l",
    "Baden 1112 Weissburgunder trocken weiß, Flasche, 0,75 l",
    "Baden Betschgräbler Riesling trocken weiß, Flasche, 1,00 l",
    "Baden Kaiserstühler Winzer vom silberberg Spätburgunder, Flasche, 1,00 l",
    "Baden Bahlinger Müller-Thurgau QbA trocken weiß, Flasche, 1,00 l",
    "Baden Bötzinger Müller-Thurgau QbA trocken weiß, Flasche, 1,00 l",
    "Baden Bötzinger Grauer Burgunder trocken weiß, Flasche, 0,75 l",
    "Baden Bötzinger Rivaner trocken weiß, Flasche, 0,75 l",
    "Baden Bötzinger Spätburgunder Rosé trocken rosé, Flasche, 0,75 l",
    "Baden Bötzinger Spätburgunder Rot trocken rot, Flasche, 0,75 l",
    "Baden Bötzinger Spätburgunder QbA mild rot, Flasche, 1,00 l",
    "Baden Bötzinger Spätburgunder QbA trocken rot, Flasche, 1,00 l",
    "Baden Collection \"O\" Spätburgunder trocken rot, Flasche, 0,75 l",
    "Baden Eisentaler Betschgräbler Riesling halbtrocken, Flasche, 1,00 l",
    "Baden Freiburger Lorettoberg Gutedel, Flasche, 1,00 l",
    "Baden Freischütz Müller-Thurgau, Flasche, 1,00 l",
    "Baden Gosch Inselbrise Blanc de Blancs trocken, Flasche, 0,75 l",
    "Baden Gosch Inselbrise Rosé halbtrocken, Flasche, 0,75 l",
    "Baden Pfaffenweiler Weisser Gutedel QbA trocken weiß, Flasche, 1,00 l",
    "Baden Hagnauer Sonnenufer Müller-Thurgau, Flasche, 0,75 l",
    "Baden Hagnauer Burgstall Spätburgunder QbA halbtrocken, Flasche, 0,75 l",
    "Hecklinger Burger Lichteneck QbA weiß, Flasche, 1,00 l",
    "Baden Ihringer Vulkanfelsen Spätburgunder halbtrocken rot, Flasche, 1,00 l",
    "Baden Ihringer Vulkanfelsen, Flasche, 1,00 l",
    "Baden Spätburgunder trocken rot, Flasche, 0,75 l",
    "Sachsen Meissen Müller-Thurgau QbA halbtrocken weiß, Flasche, 0,75 l",
    "Sachsen Meissen Müller-Thurgau QbA trocken, Flasche, 0,75 l",
    "Sachsen Meißen Riesling QbA halbtrocken weiß, Flasche, 0,75 l",
    "Sachsen Meißen Scheurebe QbA halbtrocken weiß, Flasche, 0,75 l",
    "Sachsen Meißen Spätburgunder QbA trocken rosé, Flasche, 0,75 l",
    "Sachsen Spätburgunder Ber. Meissen 2004 Spätburgunder QbA trocken rot, Flasche, 0,75 l",
    "Baden Oberrotweiler Käsleberg QbA trocken weiß, Flasche, 1,00 l",
    "Baden Oberrotweiler Käsleberg Müller-Thurgau weiss, Flasche, 1,00 l",
    "Baden Freischütz Müller-Thurgau QbA halbtrocken weiß, Flasche, 1,00 l",
    "Baden Freischütz Müller-Thurgau QbA trocken weiß, Flasche, 1,00 l",
    "Baden Vom Kaiserstuhl Müller-Thurgau halbtrocken weiß, Flasche, 1,00 l",
    "Baden Vom Kaiserstuhl Müller-Thurgau trocken weiß, Flasche, 1,00 l",
    "Württemberg Besigheimer Felsengarten Riesling QbA trocken weiß, Flasche, 1,00 l",
    "Württemberg Besigheimer Felsengarten, Flasche, 1,00 l",
    "Württemberg Besigheimer Felsengarten Kerner QbA halbtrocken weiß, Flasche, 1,00 l",
    "Württemberg Fleiner Altenberg Riesling QbA, Flasche, 1,00 l",
    "Württemberg Heilbronner Staufenberg Schwarzriesling, Flasche, 1,00 l",
    "Württemberg Heilbronner Stiftsberg Riesling QbA mild, Flasche, 1,00 l",
    "Württemberg Heilbronner Stiftsberg Trollinger QbA tr., Flasche, 1,00 l",
    "Württemberg Haberschlachter Heuchelberg k.a. QbA halbtrocken rot, Flasche, 1,00 l",
    "Württemberg Haberschlachter Heuchelberg Trollinger rot, Flasche, 1,00 l",
    "Württemberg Haberschlachter Heuchelberg Schwarzriesling rot, Flasche, 1,00 l",
    "Württemberg Heilbronner Staufenberg Spätburgunder rosé, Flasche, 1,00 l",
    "Württemberg Fleiner Kirchenweinberg Schwarzriesling QbA, Flasche, 1,00 l",
    "Württemberg Stettener Heuchelberg Riesling QbA, Flasche, 1,00 l",
    "Württemberg VierViertel Müller-Thurgau halbtrocken weiß, Flasche, 1,00 l",
    "Baden Martin Schongauer Grauer Burgunder trocken weiß, Flasche, 0,25 l",
    "Baden Martin Schongauer Weißer Burgunder trocken weiß, Flasche, 0,25 l",
    "Franken Volkacher Kirchberg Müller-Thurgau QbA, Flasche, 0,25 l",
    "Blanchet Cuvée VdF weiß, Flasche, 0,25 l",
    "Grand Sud Merlot VdP rot, Flasche, 0,25 l",
    "Frankreich Le Patron trocken rosé, Flasche, 0,25 l",
    "Frankreich Le Patron trocken rot, Flasche, 0,25 l",
    "Italien Doppio Passo Primitivo Puglia trocken rot, Flasche, 0,25 l",
    "Italien Sovinello Secco Bianco, Flasche, 0,25 l",
    "Italien Sovinello Secco Rosato, Flasche, 0,25 l",
    "Viala Rotwein Cuvée VDT rot, Flasche, 0,25 l",
    "Viala Weißwein Cuvée VDT, Flasche, 0,25 l",
    "Pfalz Rotkäppchen Dornfelder halbtrocken rot, Flasche, 0,25 l",
    "Pfalz Rotkäppchen Müller Thurgau halbtrocken weiß, Flasche, 0,25 l",
    "Pfalz Wegner Dornfelder QbA trocken rot, Flasche, 0,25 l",
    "Wegner Grauer Burgunder QbA weiß, Flasche, 0,25 l",
    "Wegner Rosé QbA rosé, Flasche, 0,25 l",
    "Bree Merlot QbA rot, Flasche, 0,25 l",
    "Bree Pinot Noir Spätburgunder QbA rosé, Flasche, 0,25 l",
    "Rheinhessen Maybach Weisser Burgunder QbA trocken weiß, Flasche, 0,25 l",
    "Württemberg Heilbronner Staufenberg Riesling, Flasche, 0,25 l",
    "Württemberg Heilbronner Staufenberg Spätburgunder, Flasche, 0,25 l",
    "Württemberg Heilbronner Staufenberg Trollinger QbA halbtrocken rot, Flasche, 0,25 l",
    "Württemberg Heilbronner Staufenberg Trollinger und Lemberger, Flasche, 0,25 l",
    "Blanchet Blanc de Blancs Tafelwein weiß VdF, Flasche, 0,75 l",
    "Frankreich Blanchet Chardonnay Trocken VdF, Flasche, 0,75 l",
    "Frankreich Blanchet Jolie Blanc de Blancs lieblich weiß, Flasche, 0,75 l",
    "Blanchet Cuvée VdF weiß, Flasche, 0,75 l",
    "Frankreich Cremant de Loire Blanc herb weiß, Flasche, 0,75 l",
    "Frankreich Cremant de Loire weiß, Flasche, 0,75 l",
    "Frankreich Grand Sud Chardonnay VdP d\u0027Oc trocken weiß, PET-Flasche, 3,00 l",
    "Grand Sud Chardonnay VdP weiß, Flasche, 1,00 l",
    "Frankreich Jean Maitré Colombard Sauvignon blanc weiß, Flasche, 0,75 l",
    "Frankreich Le Patron weiß trocken, Flasche, 1,00 l",
    "Frankreich Maison Castel Sauvignon Blanc trocken weiß, Flasche, 0,75 l",
    "Franken Silvaner die Jungen Frank\u0027n QbA trocken weiß, Flasche, 0,75 l",
    "Frankreich Rocher Cabernet Sauvignon IGP trocken rot, Flasche, 1,00 l",
    "Frankreich Blanchet Jolie Rosé de France lieblich, Flasche, 0,75 l",
    "Blanchet Rosé Cuvée VdF, Flasche, 0,75 l",
    "Frankreich Grand Sud Merlot DOC halbtrocken rosé, Flasche, 1,00 l",
    "Frankreich Jean Maitré Cinsault Grenache halbtrocken rosé, Flasche, 0,75 l",
    "Frankreich Mlle Ladubay Crémant de Loire trocken rosé, Flasche, 0,75 l",
    "Auberge Jean Maitre Cinsault Grenache Vin de Pays halbtrocken rosé, Flasche, 0,75 l",
    "Auberge Jean Maitre Merlot Vin de Pays halbtrocken rot, Flasche, 0,75 l",
    "Frankreich LE Patron rosé trocken, Flasche, 1,00 l",
    "Frankreich Le Sweet Filou Rosé trocken, Flasche, 0,75 l",
    "Frankreich Miraval Côtes de Provence trocken rosé, Flasche, 0,75 l",
    "Frankreich Entrecote Merlot Cabernet Landwein trocken rot, Box, 3,00 l",
    "Frankreich Blanchet Merlot Trocken VdF, Flasche, 0,75 l",
    "Blanchet Rouge Cuvée VdF, Flasche, 0,75 l",
    "Frankreich Bordeaux Jean Maitre AOP trocken rot, Flasche, 0,75 l",
    "Bordeaux Rothsch AOC rot, Flasche, 0,75 l",
    "Bree Merlot QbA rot, Flasche, 0,75 l",
    "Côtes du Rhône AOC rot, Flasche, 0,75 l",
    "Frankreich Entrecote Merlot Cabernet IGP halbtrocken rot, Flasche, 0,75 l",
    "Grand Sud Grenache VdP rot, Flasche, 1,00 l",
    "Frankreich Grand Sud Merlot DOC rot, PET-Flasche, 3,00 l",
    "Frankreich Grand Sud Merlot Vin de Pays d\u0027Oc trocken rot, Flasche, 1,00 l",
    "Frankreich Jean Maitré Cabernet Sauvignon Syrah halbtrocken rot, Flasche, 0,75 l",
    "Frankreich Jean Maitré Merlot VdF halbtrocken rot, Flasche, 0,75 l",
    "Frankreich Käfer Merlot trocken rot, Flasche, 0,75 l",
    "Frankreich Le Patron rot trocken, Flasche, 1,00 l",
    "Frankreich Le Sweet Filou Cuvée Landwein süß weiß, Flasche, 0,75 l",
    "Frankreich Le Sweet Filou VdT lieblich rot, Flasche, 0,75 l",
    "Les Maison Castel Syrah trocken rot, Flasche, 0,75 l",
    "Frankreich Merlot Wine Box trocken rot, Box, 3,00 l",
    "Frankreich Rocher Merlot IGP trocken rot, Flasche, 1,00 l",
    "Domkellerstolz Tafelwein rot, PET-Flasche, 1,00 l",
    "Domkellerstolz Tafelwein weiß, PET-Flasche, 1,00 l",
    "Italien Bauernwein Ital.Weißwein Vino da Tavola, Flasche, 2,00 l",
    "BioRebe Chardonnay Vegan IGP trocken weiß, Flasche, 0,75 l",
    "BioRebe Pinot Grigio Vegan IGP trocken weiß, Flasche, 0,75 l",
    "Italien Biorebe Pinot Grigio trocken weiß, Flasche, 0,25 l",
    "Italien Mezzacorona Trentino Chardonnay D.O.C., Flasche, 0,75 l",
    "ITA Doppio Passo Primitivo Alkoholfrei rot, Flasche, 0,75 l",
    "Italien Doppio Passo Grillo D.O.C. halbtrocken weiß, Flasche, 0,75 l",
    "Italien Frascati Vina Augusta DOC trocken weiß, Flasche, 0,75 l",
    "Italien Il Sole Grillo Sicilia D.O.C. trocken weiß, Flasche, 0,75 l",
    "Italien Käfer Pinot Grigio, Flasche, 0,75 l",
    "Italien Lambrusco dell\u0027Emilia lieblich rot, Flasche, 1,50 l",
    "Italien Latentia Pinot Grigio Friuli trocken weiß, Flasche, 0,75 l",
    "Italien Lunatio di Masi Lugana BIO DOC trocken weiß, Flasche, 0,75 l",
    "Montecelli Pinot Grigio IGT weiß, Flasche, 0,75 l",
    "Italien Pecorino Terre di Chieti trocken weiß, Flasche, 0,75 l",
    "Italien Pinot Grigio delle Venezie IGT trocken weiß, Flasche, 0,75 l",
    "Italien Collezione Pinot Grigio trocken weiß, Flasche, 0,75 l",
    "Italien Trentino Pinot Grigio Mezzacorona D.O.C., Flasche, 0,75 l",
    "Italien Riondo Pinot Grigio delle Venezie IGT, Flasche, 0,75 l",
    "Italien Riondo Soave weiß DOC, Flasche, 0,75 l",
    "Italien Santa Margherita Lugana DOC trocken weiß, Flasche, 0,75 l",
    "Viala Veneto IGT weiß, Flasche, 0,75 l",
    "Viala Sweet Cuvée VDT weiß, Flasche, 0,75 l",
    "Italien Vina Augusta Chardonnay IGT halbtrocken weiß, Flasche, 0,75 l",
    "Italien Vina Augusta Garganega Pinot Grigio DOC trocken weiß, Flasche, 0,75 l",
    "Italien Doppio Passo Rosato Primitivo trocken rosè, Flasche, 0,75 l",
    "Viala Sweet Rosato Cuvée VDT rosé, Flasche, 0,75 l",
    "Italien Bardolino Danese DOC trocken rot, Flasche, 0,75 l",
    "Italien Bauernwein Ital. Rotwein Vino da Tavola, Flasche, 2,00 l",
    "BioRebe Merlot Vegan IGP trocken rot, Flasche, 0,75 l",
    "Italien Biorebe Merlot trocken rot, Flasche, 0,25 l",
    "Italien Ca dei Frati Ronchedone trocken rot, Flasche, 0,75 l",
    "Italien Caleo Primitivo IGT trocken rot, Flasche, 0,75 l",
    "Chianti Riserva Villa Calappiano DOCG rot, Flasche, 0,75 l",
    "Italien Chianti Gocce Santa DOCG trocken rot, Flasche, 0,75 l",
    "Italien Doppio Passo Moscato D.O.C. halbtrocken weiß, Flasche, 0,75 l",
    "Italien Doppio Passo Primitivo Puglia IGT halbtrocken rot, Flasche, 0,75 l",
    "Italien Il Sole Montepulciano BIO D.O.C. trocken rot, Flasche, 0,75 l",
    "Italien Kalterersee Sellaronda DOC trocken rot, Flasche, 0,75 l",
    "Italien Latentia Primitivo Puglia IGT halbtrocken rot, Flasche, 0,75 l",
    "Italien Le Chiantigiane Montepulciano Rot d\u0027Abruzzo DOC, Flasche, 0,75 l",
    "Italien Collezione Merlot trocken rot, Flasche, 0,75 l",
    "Italien Merlot Trentino Mezzacorona D.O.C. trocken, Flasche, 0,75 l",
    "Italien Momenti Andrero Syrah IGP halbtrocken rot, Flasche, 0,75 l",
    "Italien Monte Bianco süß \u0026 fruchtig süß weiß, Flasche, 0,75 l",
    "Merlot IGT halbtrocken rot, Flasche, 0,75 l",
    "Bardolino DOC trocken rot, Flasche, 0,75 l",
    "Chardonnay IGT halbtrocken weiß, Flasche, 0,75 l",
    "Frascati DOC trocken rot, Flasche, 0,75 l",
    "Garganega Pinot Grigio DOC trocken weiß, Flasche, 0,75 l",
    "Italien Monte Rosato süß \u0026 fruchtig süß rosé, Flasche, 0,75 l",
    "Italien Monte Rosso süß \u0026 fruchtig VdT rot, Flasche, 0,75 l",
    "Italien Nero d\u0027Avola Caleo D.O.C. trocken rot, Flasche, 0,75 l",
    "Italien Primitivo Apulien Astro IGP halbtrocken rot, Flasche, 0,75 l",
    "Italien Primitivo di Marina 14 trocken rot, Flasche, 0,75 l",
    "Italien Primitivo Negroamaro trocken rot, Flasche, 0,75 l",
    "Italien Riondo Merlot delle Venezie IGT, Flasche, 0,75 l",
    "Viala Rotwein Sangiovese VDT trocken rot, Flasche, 0,75 l",
    "Italien Vina Augusta Bardolino DOC trocken rot, Flasche, 0,75 l",
    "Italien Vina Augusta Primitivo IGT trocken rot, Flasche, 0,75 l",
    "Italien Vina Augusta Merlot IGT halbtrocken rot, Flasche, 0,75 l",
    "Italien Vina Augusta Chianti DOCG trocken rot, Flasche, 0,75 l",
    "Chianti trocken rot, Flasche, 0,75 l",
    "Primitivo IGT halbtrocken rot, Flasche, 0,75 l",
    "Lambrusco frizzante lieblich rot, Flasche, 0,75 l",
    "Secco Frizzante, Flasche, 0,75 l",
    "Spanien El Coto Viura Sauvignon Blanc Verdejo D.O.Ca. trocken weiß, Flasche, 0,75 l",
    "Spanien El Coto Verdejo D.O.Ca. trocken weiß, Flasche, 0,75 l",
    "Spanien Mederano Blanco Cuvée weiß, Flasche, 0,75 l",
    "Spanien El Coto Rosé Tempranillo D.O.Ca. trocken rosé, Flasche, 0,75 l",
    "Mederano Rosado Cuvée rosé, Flasche, 0,75 l",
    "Spanien Natureo Rosado alkoholfrei halbtrocken rosé, Flasche, 0,75 l",
    "Amselkeller Cuvée rot, Flasche, 0,75 l",
    "Spanien Baron de Ley Reserva trocken rot, Flasche, 0,75 l",
    "BioRebe Tempranillo Vegan DO rot, Flasche, 0,75 l",
    "Spanien El Cotillo Tinto Semidulce 100% vol. Tempranillo Tierra de Castilla lieblich rot, Flasche, 0,75 l",
    "Spanien El Cotillo Tinto Semiseco 100% vol. Tempranillo Tierra de Castilla halbtrocken rot, Flasche, 0,75 l",
    "Spanien El Cotillo Tinto Seco 100% vol. Tempranillo Tierra de Castilla trocken rot, Flasche, 0,75 l",
    "Spanien El Coto Crianza Tempranillo D.O.Ca. trocken rot, Flasche, 0,75 l",
    "Spanien Mederano Tinto Cuvée rot, Flasche, 0,75 l",
    "Spanien Tempranillo Wine Box, Box, 3,00 l",
    "Portugal Marques de Borba Colheita trocken rot, Flasche, 0,75 l",
    "Portugiesischer Rosé Cuvée VdT, Flasche, 1,00 l",
    "Österreich Blauer Zweigelt- Weinmanufaktur Krems, Flasche, 0,75 l",
    "Österreich Blauer Zweigelt Blauer Zweigelt Qualitätswein trocken rot, Flasche, 1,00 l",
    "Österreich Edition Chremisa Grüner Veltliner trocken weiß, Flasche, 0,75 l",
    "Österreich Grüner Veltliner Weinmanufaktur Krems, Flasche, 0,75 l",
    "Österreich Heuriger Grüner Veltliner, Flasche, 1,00 l",
    "Österreich Sandgrube 13 Weißburgunder QbA trocken weiß, Flasche, 0,75 l",
    "Sandgrube 13 Blauer Zweigelt trocken rot, Flasche, 0,75 l",
    "Sandgrube 13 Grüner Veltiner trocken weiß, Flasche, 0,75 l",
    "Österreich Sandgrube 13 Zweigelt Rosé QmgH trocken, Flasche, 0,75 l",
    "Mazedonien Mazenoro Vranec Kadarka lieblich rot, Flasche, 1,00 l",
    "Rumänien Meat Love Chardonnay trocken weiß, Flasche, 0,75 l",
    "Schwarze Mädchentraube Merlot QmgH rot, Flasche, 0,75 l",
    "Imiglikos Nemea QmgH rot, Flasche, 0,75 l",
    "Südafrika Cape Africa trocken rot, Flasche, 0,75 l",
    "Südafrika Cape Coast Chenin Blanc QmgH trocken weiß, Flasche, 0,75 l",
    "Südafrika Cape Coast Pinotage QmgH trocken rot, Flasche, 0,75 l",
    "Südafrika Chenin Blanc Wine Box, Box, 3,00 l",
    "Golden Kaan Shiraz rot, Flasche, 0,75 l",
    "Südafrika Rebourne Chenin Blanc trocken weiß, Flasche, 0,75 l",
    "SSAF Rebourne Shiraz trocken rot, Flasche, 0,75 l",
    "Kalifornien Gallo Vineyards Cabernet Sauvignon QmgH rot, Flasche, 0,75 l",
    "Kalifornien Gallo F V Chardonnay, Flasche, 0,75 l",
    "Kalifornien Gallo Family Vineyards, Flasche, 0,75 l",
    "Gallo Family Zinfandel QmgH rot, Flasche, 0,75 l",
    "Gallo Grenache QmgH rosé, Flasche, 0,75 l",
    "Kalifornien Gallo Family Vineyards Moscato süß weiß, Flasche, 0,75 l",
    "Kalifornien Gallo Spritz Himbeere süß zart rosé, Flasche, 0,75 l",
    "Western Cellars Cabernet Sauvignon QmgH rot, Flasche, 0,75 l",
    "Western Cellars Colombard QmgH weiß, Flasche, 0,75 l",
    "Chile Cabernet Sauvignon Wine Box, Box, 3,00 l",
    "El Emperador Sauvignon QmgH weiß, Flasche, 0,75 l",
    "Astra Urtyp, Dose, 0,50 l",
    "Beck\u0027s Pils, Dose, 0,50 l",
    "Beck\u0027s Gold, Dose, 0,50 l",
    "Beck\u0027s Blue, Dose, 0,50 l",
    "Benediktiner Hell, Dose, 0,50 l",
    "Berliner Kindl Jubiläums Pils, Dose, 0,50 l",
    "Berliner Pilsner, Dose, 0,50 l",
    "Binding Export, Dose, 0,50 l",
    "Binding Römer Pils, Dose, 0,50 l",
    "Bitburger Pils, Dose, 0,50 l",
    "Brinkhoff\u0027s No.1, Dose, 0,50 l",
    "Brauburger Pils, Dose, 0,50 l",
    "Diebels Alt, Dose, 0,50 l",
    "Dinkelacker Pilsner, Dose, 0,50 l",
    "Dominikaner Pils, Dose, 0,50 l",
    "Eichbaum Ureich Pils, Dose, 0,50 l",
    "Feldschlößchen Pilsner, Dose, 0,50 l",
    "Franziskaner Hefeweißbier, Dose, 0,50 l",
    "Früh Kölsch, Dose, 0,50 l",
    "Fürstenberg Premium Pilsener, Dose, 0,50 l",
    "Fürstenberg Hell, Dose, 0,50 l",
    "Gaffel Kölsch, Dose, 0,50 l",
    "Gilde Pilsener, Dose, 0,50 l",
    "Gold Ochsen Original, Dose, 0,50 l",
    "Gold Ochsen Ulmer hell, Dose, 0,50 l",
    "Grevensteiner Original, Dose, 0,50 l",
    "Grevensteiner Helles, Dose, 0,50 l",
    "Hacker Pschorr Münchner Hell, Dose, 0,50 l",
    "Hansa Pils, Dose, 0,50 l",
    "Hasseröder Premium Pils, Dose, 0,50 l",
    "Herforder Pils, Dose, 0,50 l",
    "Herrenhäuser Pilsener, Dose, 0,50 l",
    "Holsten Edel, Dose, 0,50 l",
    "Holsten Pilsener, Dose, 0,50 l",
    "Jever Pilsener, Dose, 0,50 l",
    "Kaiserdom Helles, Dose, 1,00 l",
    "Kaiserdom Lager, Dose, 1,00 l",
    "Kaiserdom Strong, Dose, 1,00 l",
    "Kaiserdom Pilsener, Dose, 1,00 l",
    "Karlsberg Urpils, Dose, 0,50 l",
    "Karlsberg Helles, Dose, 0,50 l",
    "König Pilsener, Dose, 0,50 l",
    "Köstritzer Schwarzbier, Dose, 0,50 l",
    "Krombacher Pils, Dose, 0,50 l",
    "Kronen Pilsener, Dose, 0,50 l",
    "Kulmbacher Pils, Dose, 0,50 l",
    "Leikeim Handfass Hell, Dose, 0,33 l",
    "Licher Pilsner, Dose, 0,50 l",
    "Lübzer Pils, Dose, 0,50 l",
    "Löwenbräu Original, Dose, 0,50 l",
    "Mönchshof Hell, Dose, 0,50 l",
    "Original 5.0 Pils, Dose, 0,50 l",
    "Original 5.0 Export, Dose, 0,50 l",
    "Original 5.0 Helles, Dose, 0,50 l",
    "Paderborner Hell, Dose, 0,50 l",
    "Paderborner Pilsener, Dose, 0,50 l",
    "Paderborner Pilger Landbier, Dose, 0,50 l",
    "Paulaner Hefe-Weißbier naturtrüb, Dose, 0,50 l",
    "Paulaner Original Münchner Hell, Dose, 0,50 l",
    "Pilsator, Dose, 0,50 l",
    "Pilsner Urquell, Dose, 0,50 l",
    "Radeberger Pils, Dose, 0,50 l",
    "Reissdorf Kölsch, Dose, 0,50 l",
    "Schöfferhofer Hefeweizen, Dose, 0,50 l",
    "Schultheiss Pilsener, Dose, 0,50 l",
    "Spaten hell, Dose, 0,50 l",
    "Sternburg Export, Dose, 0,50 l",
    "Stuttgarter Hofbräu Pilsner, Dose, 0,50 l",
    "Ur-Krostitzer, Dose, 0,50 l",
    "Veltins Pilsener, Dose, 0,33 l",
    "Veltins Pils, Dose, 0,50 l",
    "Warsteiner Premium Pilsener, Dose, 0,50 l",
    "Warsteiner Premium Pilsener, Dose, 0,33 l",
    "Warsteiner Brewers Gold, Dose, 0,50 l",
    "Wernesgrüner Pils, Dose, 0,50 l",
    "Wicküler Pilsener, Dose, 0,50 l",
    "Wolters Pilsner, Dose, 0,50 l",
    "Wulle Vollbier hell, Dose, 0,50 l",
    "Bruderkuss Lagerbier Vol. 4 9%, Dose, 0,50 l",
    "Budweiser Budvar, Dose, 0,50 l",
    "Carlsberg Beer, Dose, 0,33 l",
    "Carlsberg Elephant Beer 7.5% vol., Dose, 0,50 l",
    "Coors, Dose, 0,50 l",
    "Corona Extra, Dose, 0,33 l",
    "Desperados, Dose, 0,50 l",
    "Desperados XL Original, Flasche, 0,65 l",
    "Efes Pilsener, Dose, 0,50 l",
    "Estrella Galicia, Dose, 0,33 l",
    "Carlsberg Elephant Extra strong 10.5% vol., Dose, 0,50 l",
    "Faxe Extra Strong 10% Vol, Dose, 1,00 l",
    "Faxe Danish Lager Beer, Dose, 0,50 l",
    "Faxe Danish Lager Beer, Dose, 1,00 l",
    "Heineken Can, Dose, 0,33 l",
    "Heineken, Dose, 0,50 l",
    "Heineken Can 0.0% Alkoholfrei, Dose, 0,33 l",
    "Miller Genuine, Dose, 0,50 l",
    "Ozujsko Helles Lager, Dose, 0,50 l",
    "San Miguel, Dose, 0,33 l",
    "Tuborg Pilsener, Dose, 0,50 l",
    "Tyskie, Dose, 0,50 l",
    "Astra Granate Energy 0.0%, Dose, 0,33 l",
    "Bitburger Pils Alkoholfrei 0 0%, Dose, 0,50 l",
    "Bitburger Radler Alkoholfrei, Dose, 0,50 l",
    "Clausthaler Original, Dose, 0,50 l",
    "Gösser Natur Radler 0.0%, Dose, 0,50 l",
    "Dominikaner Premium Pils, Dose, 0,5 l",
    "Dominikaner Radler Naturtrüb, Dose, 0,5 l",
    "Krombacher Pils Alkoholfrei, Dose, 0,50 l",
    "2.5 Original Naturtrüb, Dose, 0,50 l",
    "Astra Kiezmische Radler, Dose, 0,33 l",
    "Astra Rakete, Dose, 0,33 l",
    "Astra Rakete XL, Dose, 0,568 l",
    "Beck\u0027s Green Lemon, Dose, 0,50 l",
    "Beck\u0027s Ice, Dose, 0,50 l",
    "Berliner Kindl Radler naturtrüb, Dose, 0,50 l",
    "Bitburger Radler, Dose, 0,50 l",
    "Bitburger Radler naturtrüb, Dose, 0,50 l",
    "Dominikaner Radler Naturtrüb, Dose, 0,50 l",
    "Flötzinger Cola Mix, Dose, 0,33 l",
    "Früh Naturradler, Dose, 0,50 l",
    "Gaffel Lemon, Dose, 0,50 l",
    "Gaffel Fassbrause, Dose, 0,50 l",
    "Gösser Natur Radler, Dose, 0,50 l",
    "Karlsberg Natur Radler, Dose, 0,50 l",
    "Krombacher Natur Radler, Dose, 0,50 l",
    "Krombacher Radler, Dose, 0,50 l",
    "Krombacher Spezi, Dose, 0,50 l",
    "Licher X 2 Cola, Dose, 0,50 l",
    "Leikeim Cola Mix, Dose, 0,33 l",
    "Lübzer Grapefruit, Dose, 0,50 l",
    "Lübzer Naturradler, Dose, 0,50 l",
    "Mixery Bier X Cola, Dose, 0,50 l",
    "Mixery Cherry, Dose, 0,50 l",
    "Mixery Lemon, Dose, 0,50 l",
    "Mixery iced purple, Dose, 0,50 l",
    "Mixery iced yellow, Dose, 0,50 l",
    "MiXery Nastrov Flavour iced blue, Dose, 0,50 l",
    "Mixery Ultimate Energy, Dose, 0,33 l",
    "Mixery Ultimate Lemon, Dose, 0,33 l",
    "Mixery Ultimate Original, Dose, 0,33 l",
    "Mönchshof Natur Radler, Dose, 0,50 l",
    "Paulaner Natur Radler, Dose, 0,50 l",
    "Schöfferhofer Grapefruit, Dose, 0,50 l",
    "Stuttgarter Hofbräu Radler naturtrüb, Dose, 0,50 l",
    "Tyskie Radler, Dose, 0,50 l",
    "Veltins Radler, Dose, 0,50 l",
    "Veltins Fassbrause Eistee, Dose, 0,50 l",
    "Veltins Fassbrause Cola-Orange, Dose, 0,50 l",
    "Veltins V + Apple, Dose, 0,50 l",
    "Veltins V + Berry 5% vol. Alk., Dose, 0,50 l",
    "Veltins V + Curuba, Dose, 0,50 l",
    "Veltins V + Sprizz, Dose, 0,50 l",
    "Veltins V + Lemon 5% vol. Alk., Dose, 0,50 l",
    "Veltins V + Energy 5% vol., Dose, 0,50 l",
    "Warsteiner Radler, Dose, 0,50 l",
    "Mixery Ultimate Iced Tea Lemon, PET-Flasche, 0,50 l",
    "Mixery Ultimate Iced Tea Peach, PET-Flasche, 0,50 l",
    "Karamalz Classic, Dose, 0,33 l",
    "Vitamalz, Dose, 0,33 l",
    "Bitburger Premium Pils, Dose, 5,00 l",
    "Budweiser Budvar Premium Lager 2x5l Partydose, Dose, 5,00 l",
    "Früh Kölsch, Dose, 5,00 l",
    "Krombacher Pils, Dose, 5,00 l",
    "Paulaner Hefe-Weißbier naturtrüb, Dose, 5,00 l",
    "Reissdorf Kölsch Partydose, Dose, 5,00 l",
    "Rothaus Pils, Dose, 5,00 l",
    "Warsteiner Pils, Dose, 5,00 l",
    "Astra Pils Urtyp, Flasche, 0,33 l",
    "Astra Pils Urtyp, Flasche, 0,50 l",
    "Beck\u0027s Bier, Flasche, 0,33 l",
    "Beck\u0027s Gold, Flasche, 0,33 l",
    "Beck´s Gold, Flasche, 0,50 l",
    "Beck\u0027s Pils, Flasche, 0,50 l",
    "Berliner Kindl Jubiläum, Flasche, 0,50 l",
    "Flensburger Pils Bügel, Flasche, 0,33 l",
    "Berliner Pilsner, Flasche, 0,50 l",
    "Berliner Pranke, Flasche, 0,50 l",
    "Binding Römer Pils, Flasche, 0,50 l",
    "Bitburger Pils Premium, Flasche, 0,50 l",
    "Eichbaum Pilsener, Flasche, 0,50 l",
    "Flensburger Gold, Flasche, 0,33 l",
    "Flensburger Pils Bügel, Flasche, 0,50 l",
    "Fürstenb Pilsener, Flasche, 0,50 l",
    "Gold Ochsen Original, Flasche, 0,50 l",
    "Gold Ochsen Ulmer Hell, Flasche, 0,50 l",
    "Haake Beck Pils, Flasche, 0,50 l",
    "Hasseröder Pils, Flasche, 0,50 l",
    "Herrenhäuser Pils, Flasche, 0,50 l",
    "Holsten Edel, Flasche, 0,33 l",
    "Holsten Edel, Flasche, 0,50 l",
    "Holsten Pils, Flasche, 0,50 l",
    "Jever Pilsener, Flasche, 0,50 l",
    "Karlsberg Urpils, Flasche, 0,50 l",
    "König Pilsener, Flasche, 0,50 l",
    "Krombacher Pils, Flasche, 0,50 l",
    "Kulmbacher Edelherb Pils, Flasche, 0,50 l",
    "Licher Pils, Flasche, 0,50 l",
    "Lübzer Pils, Flasche, 0,50 l",
    "Oettinger Privat Pils, Flasche, 0,50 l",
    "Paderborner Hell, Flasche, 0,50 l",
    "Paderborner Pilsener, Flasche, 0,50 l",
    "Pilsator Pilsener, Flasche, 0,50 l",
    "Radeberger Pils, Flasche, 0,50 l",
    "Ratsherrn Pils, Flasche, 0,33 l",
    "Rothaus Pils, Flasche, 0,50 l",
    "Schultheiss Pils, Flasche, 0,50 l",
    "Stuttgarter Hofbräu Pilsener, Flasche, 0,50 l",
    "Ur-Krostitzer, Flasche, 0,50 l",
    "Veltins Pils, Flasche, 0,50 l",
    "Warsteiner Pils, Flasche, 0,50 l",
    "Wolters Premium Pilsner, Flasche, 0,50 l",
    "Binding Export, Flasche, 0,50 l",
    "Dortmunder Union Export, Flasche, 0,50 l",
    "Eichbaum Export, Flasche, 0,50 l",
    "Licher Export, Flasche, 0,50 l",
    "Oettinger Export, Flasche, 0,50 l",
    "Paderborner Export, Flasche, 0,50 l",
    "Sternburg Export, Flasche, 0,50 l",
    "Stuttgarter Hofbräu Premium Export, Flasche, 0,50 l",
    "Augustiner Edelstoff LG, Flasche, 0,50 l",
    "Augustiner hell LG, Flasche, 0,50 l",
    "Diebels Alt, Flasche, 0,50 l",
    "Früh Kölsch, Flasche, 0,50 l",
    "Gaffel Kölsch, Flasche, 0,50 l",
    "Hacker Pschorr Münchner Hell Bügelverschluß, Flasche, 0,50 l",
    "Reissdorf Kölsch, Flasche, 0,50 l",
    "Reissdorf Kölsch, Flasche, 0,33 l",
    "Rothaus Märzen, Flasche, 0,50 l",
    "Wulle Vollbier hell BV, Flasche, 0,33 l",
    "Budweiser, Flasche, 0,50 l",
    "Corona Extra im Karton, Flasche, 0,355 l",
    "Desperados, Flasche, 0,33 l",
    "Desperados XL, Flasche, 0,65 l",
    "Gösser Naturradler, Flasche, 0,50 l",
    "Hefeweizen trüb, Flasche, 0,50 l",
    "Franziskaner Hefeweissbier Naturtrüb, Flasche, 0,50 l",
    "Paulaner Hefeweizen trüb, Flasche, 0,50 l",
    "Rothaus Hefeweizen Hell, Flasche, 0,50 l",
    "Schöfferhofer Hefeweizen trüb, Flasche, 0,50 l",
    "Spaten Münchner Hell, Flasche, 0,50 l",
    "Rothaus Hefeweizen alkoholfrei, Flasche, 0,50 l",
    "Flensburger Radler, Flasche, 0,33 l",
    "Hacker Pschorr Münchner Radler Bügelverschluß, Flasche, 0,50 l",
    "Beck\u0027s Green Lemon, Flasche, 0,33 l",
    "Bundaberg Ginger Brew im Karton, Flasche, 0,33 l",
    "MiXery Cola, Flasche, 0,50 l",
    "Absolut Berry Fizz 10% vol., Dose, 0,33 l",
    "Absolut Pineapple Fizz 10% vol., Dose, 0,33 l",
    "Bacardi \u0026 Cola 10% vol., Dose, 0,25 l",
    "Bacardi Cuba Libre 10% vol., Dose, 0,25 l",
    "Bacardi Limon \u0026 Lemonade 10% vol., Dose, 0,25 l",
    "Bacardi Mojito 10% vol., Dose, 0,25 l",
    "Bacardi Pina Colada 10% vol., Dose, 0,25 l",
    "Bacardi Razz Mojito 10% vol., Dose, 0,25 l",
    "Bacardi Spiced \u0026 Cola 10% vol., Dose, 0,25 l",
    "Belsazar Rose \u0026 Tonic 5.5% vol., Dose, 0,25 l",
    "Bombay Bramble Gin \u0026 Tonic 10% vol., Dose, 0,25 l",
    "Bombay Dry \u0026 Tonic 10% vol., Dose, 0,25 l",
    "Bombay Sapphire Gin \u0026 Tonic 10% vol., Dose, 0,25 l",
    "Bombay Pressé Citrus Collins 10% vol., Dose, 0,25 l",
    "Captain Morgan White \u0026 Mojito 10% vol., Dose, 0,25 l",
    "Captain Morgan Spiced Gold \u0026 Cola 10% vol., Dose, 0,25 l",
    "Gentleman Jack \u0026 Cola 10% vol., Dose, 0,33 l",
    "Jack Daniel\u0027s Gentleman Jack Whiskey Sour 10% vol., Dose, 0,33 l",
    "Gorbatschow Sex on the Beach 10% vol., Dose, 0,33 l",
    "Gorbatschow Energy 10% vol., Dose, 0,33 l",
    "Gorbatschow \u0026 Lemon 10% vol., Dose, 0,33 l",
    "Gorbatschow \u0026 Maracuja 10% vol., Dose, 0,33 l",
    "Gordon\u0027s Gin \u0026 Tonic 10% vol., Dose, 0,25 l",
    "Gordon\u0027s Pink Gin \u0026 Tonic 10% vol., Dose, 0,25 l",
    "Grasovka Vodka Apple Soda 10% vol., Dose, 0,33 l",
    "Havana Club Cane Sugar \u0026 Lime 10% vol., Dose, 0,33 l",
    "Havana Club Cuban Spiced \u0026 Cola 10% vol., Dose, 0,33 l",
    "Havana Club Cuban Rum \u0026 Cola 10% vol., Dose, 0,33 l",
    "St.Hubertustropfen Hubi plus Cola 10% vol., Dose, 0,25 l",
    "Jack Daniel\u0027s \u0026 Berry 10% vol., Dose, 0,33 l",
    "Jack Daniel\u0027s \u0026 Ginger 10% vol., Dose, 0,33 l",
    "Jack Daniel\u0027s Lynchburg Lemonade 10% vol., Dose, 0,33 l",
    "Jack Daniel\u0027s \u0026 Coca-Cola 10% vol., Dose, 0,33 l",
    "Jack Daniel\u0027s \u0026 Cola 10% Vol, Dose, 0,33 l",
    "Jack Daniel\u0027s \u0026 Coca-Cola Zero 10% vol., Dose, 0,33 l",
    "Jim Beam Black Cherry 10% vol., Dose, 0,33 l",
    "Jim Beam \u0026 Cola 10% vol., Dose, 0,33 l",
    "Jim Beam Lime Splash 10%, Dose, 0,33 l",
    "Jim Beam White \u0026 Cola Zero 10% vol., Dose, 0,33 l",
    "Johnnie Walker \u0026 Cola 10% vol., Dose, 0,25 l",
    "Kaleu\u0027s Wodka Waldmeister 10% vol., Dose, 0,33 l",
    "Mangaroca Batida Passion mit Maracuja 10% vol., Dose, 0,25 l",
    "Licor 43 Coco Milk 10% vol., Dose, 0,25 l",
    "Licor 43 Nitro \u0026 Coffee 10% vol., Dose, 0,20 l",
    "Licor 43 Milk 10% vol., Dose, 0,25 l",
    "Malibu Pineapple 10% vol., Dose, 0,25 l",
    "Malibu Watermelon 10% vol., Dose, 0,25 l",
    "Martini Fiero \u0026 Tonic 4.7% vol., Dose, 0,25 l",
    "MSK-Moskovskaya \u0026 Lemon 10% vol., Dose, 0,33 l",
    "Needle Black Forest Distilled Dry Gin \u0026 Tonic 10% vol., Dose, 0,33 l",
    "Oldesloer Weizenkorn \u0026 Cola 10 3% vol., Dose, 0,25 l",
    "Pallini Limoncello Spritz 10.5% vol., Dose, 0,25 l",
    "Pitu Brazilian Mojito 10% vol., Dose, 0,33 l",
    "Pitu Caipirinha 10% vol., Dose, 0,33 l",
    "Pitu Passionfruit Caipirinha 10% vol., Dose, 0,33 l",
    "Smirnoff Ice 10% vol., Dose, 0,25 l",
    "Southern Comfort \u0026 Cola 10% vol., Dose, 0,33 l",
    "Southern Comfort Lemonade \u0026 Lime 10% vol., Dose, 0,33 l",
    "Tanqueray \u0026 Tonic zero 0.0%, Dose, 0,25 l",
    "Tanqueray London Dry Gin \u0026 Tonic 10% vol., Dose, 0,25 l",
    "Three Sixty Vodka Dark Berry 10% vol., Dose, 0,33 l",
    "Three Sixty Vodka Energy 10% vol., Dose, 0,33 l",
    "Three Sixty Vodka Ice Tea Peach 10% vol., Dose, 0,33 l",
    "Wodka-E 10% vol., Dose, 0,33 l",
    "Wood Stork Spiced Rum \u0026 Cola 10% vol., Dose, 0,33 l",
    "Katlenburger Tropica Sex on the Beach, Flasche, 0,75 l",
    "Ustinoff Ice + Lemon 5.9% vol., Flasche, 0,275 l",
    "Jack Daniel\u0027s \u0026 Cola 10% vol., Dose, 0,33 l",
    "Cafemio Cappuccino, Flasche, 0,25 l",
    "Cafemio Macchiato, Flasche, 0,25 l",
    "Nescafé RTD Espresso Macchiato, Dose, 0,25 l",
    "Nescafé RTD Cappuccino, Dose, 0,25 l",
    "Nescafé RTD Latte, Dose, 0,25 l",
    "Nescafé RTD Latte Caramel, Dose, 0,25 l",
    "Mr. Brown Caramel Latte, Dose, 0,25 l",
    "Mr. Brown Coffee Drink, Dose, 0,25 l",
    "Mr. Brown Cappuccino, Dose, 0,25 l",
    "Mr. Brown Vanilla, Dose, 0,25 l",
    "Starbucks Daily Brew Vanilla, Dose, 0,25 l",
    "Starbucks Daily Brew Classic, Dose, 0,25 l",
    "Starbucks Daily Brew Chocolate, Dose, 0,25 l",
    "4BRO Bubble Gum Erfrischungsgetränk aus Weißtee- Extrakt, PET-Flasche, 0,50 l",
    "4BRO Honigmelone, PET-Flasche, 0,50 l",
    "4BRO Lemon, PET-Flasche, 0,50 l",
    "4BRO Mango Maracuja, PET-Flasche, 0,50 l",
    "4BRO Peach, PET-Flasche, 0,50 l",
    "4BRO Purple Dream, PET-Flasche, 0,50 l",
    "4BRO Ice Tea Apricot-Strawberry, PET-Flasche, 0,50 l",
    "4BRO Red Crash, PET-Flasche, 0,50 l",
    "4BRO Juiz Bubatz Maracuja Apfel Vanille, PET-Flasche, 0,50 l",
    "4BRO Juiz Strawberry Cream, PET-Flasche, 0,50 l",
    "4BRO Bubble Gum, PET-Flasche, 1,00 l",
    "4BRO Mango Maracuja, PET-Flasche, 1,00 l",
    "4BRO Peach, PET-Flasche, 1,00 l",
    "4BRO Ice Tea Bubatz Edition Drachenfrucht, PET-Flasche, 1,00 l",
    "4BRO Ice Tea Ipanema, PET-Flasche, 1,00 l",
    "BraTee Granatapfel, PET-Flasche, 0,75 l",
    "BraTee Wassermelone, PET-Flasche, 0,75 l",
    "Christinen Eistee Zitrone, PET-Flasche, 0,50 l",
    "Nordfrost Erfrischungsgetränk Granatapfel-Zitrus Block, PET-Flasche, 0,50 l",
    "Nordfrost Erfrischungsgetränk Kirsch-ZitronenT Block, PET-Flasche, 0,50 l",
    "Nordfrost meinT GraziT, PET-Flasche, 0,50 l",
    "Nordfrost meinT MultivitaminT, PET-Flasche, 0,50 l",
    "Nordfrost meinT WassermelonenT, PET-Flasche, 0,50 l",
    "Nordfrost meinT ZitronenT, PET-Flasche, 0,50 l",
    "Nordfrost Erfrischungsgetränk MultivitaminT Block, PET-Flasche, 0,50 l",
    "Nordfrost Erfrischungsgetränk OrangenT Block, PET-Flasche, 0,50 l",
    "Nordfrost Erfrischungsgetränk ZitronenT Block, PET-Flasche, 0,50 l",
    "Pfanner Eistee Wassermelone, PET-Flasche, 0,75 l",
    "Pfanner Eistee Wildkirsche, PET-Flasche, 0,75 l",
    "Pfanner Botanic Tea Himbeere- Rosmarin, PET-Flasche, 2,00 l",
    "Pfanner Eistee Mango-Maracuja, PET-Flasche, 2,00 l",
    "Pfanner Eistee Lemon-Lime, PET-Flasche, 2,00 l",
    "Pfanner Eistee Waldbeere, PET-Flasche, 2,00 l",
    "Pfanner Eistee Wassermelone, PET-Flasche, 2,00 l",
    "Pfanner Eistee Wildkirsche, PET-Flasche, 2,00 l",
    "Pfanner Der Gelbe Zitrone- Physalis, PET-Flasche, 2,00 l",
    "Pfanner Der Grüne Zitrone- Kaktusfeige, PET-Flasche, 2,00 l",
    "Pfanner Roter Tee Zitrone- Granatapfel, PET-Flasche, 2,00 l",
    "Pfanner Weißer Tee Holunder, PET-Flasche, 2,00 l",
    "QuickVit Durstlöscher Eistee mit Zitrone, PET-Flasche, 0,50 l",
    "AriZona Green Tea With Ginseng and Honey, Dose, 0,50 l",
    "AriZona Iced Tea With Peach Flavour, Dose, 0,50 l",
    "Dirtea Eistee Blueberry, Dose, 0,50 l",
    "Dirtea Eistee Candy, Dose, 0,50 l",
    "Dirtea Eistee Peach, Dose, 0,50 l",
    "fermentea’d Kombucha Coco Passion, Dose, 0,25 l",
    "fermentea’d Kombucha herbal Orange, Dose, 0,25 l",
    "Fuze Tea Blaubeere-Lavendel, Flasche, 0,40 l",
    "Fuze Tea Wassermelone-Minze, Flasche, 0,40 l",
    "Fuze Tee Blaubeere-Lavendel ohne Zucker, Flasche, 1,00 l",
    "Gerolsteiner Tee Schwarztee Zitrone, Flasche, 0,75 l",
    "Lipton Sparkling Zitrone Sleek Can, Dose, 0,33 l",
    "Lipton Zitrone, Flasche, 0,50 l",
    "Lipton Zitrone, Flasche, 1,50 l",
    "Love \u0026 Peace Tea Birne, Dose, 0,33 l",
    "Love \u0026 Peace Tea Garden Mint, Dose, 0,33 l",
    "Pfanner Eistee Lemon, Flasche, 1,50 l",
    "Rauch Eistee Berries, Dose, 0,33 l",
    "Rauch Eistee Cola Gum Orange, Dose, 0,33 l",
    "Rauch Eistee Kiwi, Dose, 0,33 l",
    "Rauch Eistee Raspberry, Dose, 0,33 l",
    "Rauch Eistee Zitrone, Dose, 0,33 l",
    "Rauch Eistee Berries, Flasche, 1,50 l",
    "Rauch Eistee Zitrone, Flasche, 1,50 l",
    "Rauch Eistee Zitrone ohne Zucker, Flasche, 1,50 l",
    "Vitavate Tee Hibiskus, Flasche, 0,50 l",
    "Volvic BIO Tee Hibiskus, Flasche, 0,75 l",
    "Volvic BIO Tee mit Zitronengeschmack, Flasche, 0,75 l",
    "Volvic Grüner Tee Zitrone, Flasche, 0,75 l",
    "Volvic Tee rote Früchte, Flasche, 0,75 l",
    "beckers bester Disney Apfel- Banane-Mango Donald \u0026 Daisy, PET-Flasche, 0,33 l",
    "beckers bester Disney Kindergetr. Milder Multi Goofy \u0026 Pluto, PET-Flasche, 0,33 l",
    "beckers bester Disney Apfel- Traube-Kirsche Minnie \u0026 Mickey, PET-Flasche, 0,33 l",
    "Granini Fruchtschorle Apfel, Flasche, 0,50 l",
    "Gerolsteiner Apfelschorle PET, Flasche, 0,75 l",
    "Gerolsteiner Leichte Schorle Apfel, Flasche, 0,75 l",
    "hella Aktiv, Flasche, 0,75 l",
    "hella apfelschorle, Flasche, 0,75 l",
    "hella Wellness, Flasche, 0,75 l",
    "Christinen Iso Sport, Flasche, 0,50 l",
    "Powerade Sports Zero Mountainblast, Flasche, 0,50 l",
    "Powerade Sports Mountainblast, Flasche, 1,00 l",
    "Powerade Passionsfrucht, Flasche, 0,50 l",
    "Sinalco Iso Sport, Flasche, 0,50 l",
    "URUS Acai - schwarze Traube Isotonisches Erfrischungsgetränk, Flasche, 0,50 l",
    "URUS Erdbeere-Ananas Zero Isotonisches Erfrischungsgetränk, Flasche, 0,50 l",
    "URUS Kiwi-Limette-Apfel Isotonisches Erfrischungsgetränk, Flasche, 0,50 l",
    "Vöslauer Sport, Flasche, 0,75 l",
    "28 Black Acai, Dose, 0,25 l",
    "28 Black Classic, Dose, 0,25 l",
    "28 Black Limette-Minze, Dose, 0,25 l",
    "28 Black Sour Mango Kiwi, Dose, 0,25 l",
    "28 Black Sour Cherry, Dose, 0,25 l",
    "4BRO Energy Chill Mint, Dose, 0,25 l",
    "AA Drink High Energy, Flasche, 0,50 l",
    "AA Drink Zero, Flasche, 0,50 l",
    "Crowns Energy classic, Dose, 0,33 l",
    "Crowns Energy Deep Berry, Dose, 0,33 l",
    "Crowns Energy Holunder, Dose, 0,33 l",
    "Dr. Pepper Energy, Dose, 0,50 l",
    "Flying Horse Energy Drink, Dose, 0,50 l",
    "Flying Horse Energy Drink, Dose, 0,25 l",
    "Gönrgy Energy Blueberry Coconut, Dose, 0,50 l",
    "Gönrgy Energy Raspberry Cheesecake, Dose, 0,50 l",
    "Gönrgy Energy Tropical Exotic, Dose, 0,50 l",
    "Monster Absolutely Zero, Dose, 0,50 l",
    "Monster Assault Energy Drink, Dose, 0,50 l",
    "Monster Energy Aussie Style Lemon, Dose, 0,50 l",
    "Monster Energy, Dose, 0,50 l",
    "Monster Energy Reserve Orange, Dose, 0,50 l",
    "Monster Energy Nitro Cosmic Peach, Dose, 0,50 l",
    "Monster Khaotic, Dose, 0,50 l",
    "Monster Lewis Hamilton Zero Sugar, Dose, 0,50 l",
    "Monster Mango Loco, Dose, 0,50 l",
    "Monster Monarch, Dose, 0,50 l",
    "Monster Mule Ginger Brew, Dose, 0,50 l",
    "Monster Energy Nitro Super Dry, Dose, 0,50 l",
    "Monster Pipeline Punch, Dose, 0,50 l",
    "Monster Rehab Lemon, Dose, 0,50 l",
    "Monster Rehab Peach, Dose, 0,50 l",
    "Monster Rossi, Dose, 0,50 l",
    "Monster Ultra Fiesta, Dose, 0,50 l",
    "Monster Ultra Gold, Dose, 0,50 l",
    "Monster Ultra Paradise, Dose, 0,50 l",
    "Monster Energy Ultra Rosa, Dose, 0,50 l",
    "Monster Ultra Watermelon, Dose, 0,50 l",
    "Monster Ultra White, Dose, 0,50 l",
    "Monster Energy Reserve Watermelon, Dose, 0,50 l",
    "Monster Energy Reserve White Pineapple, Dose, 0,50 l",
    "Power-G Energy Drink, Dose, 0,25 l",
    "Power-G Pomegranate, Dose, 0,25 l",
    "Power-G Watermelon, Dose, 0,25 l",
    "Organics by Red Bull Easy Lemon, Dose, 0,25 l",
    "Red Bull Blue Edition Heidelbeere, Dose, 0,25 l",
    "Red Bull Energy Drink, Dose, 0,25 l",
    "Red Bull Green Edition Summer Kaktusfrucht, Dose, 0,25 l",
    "Red Bull Purple Edition Acai, Dose, 0,25 l",
    "Red Bull Red Edition Wassermelone, Dose, 0,25 l",
    "Red Bull Sugarfree, Dose, 0,25 l",
    "Red Bull Sea Blue Edition Juneberry, Dose, 0,25 l",
    "Red Bull Summer Edition 2023 Juneberry, Dose, 0,25 l",
    "Red Bull Apricot Edition Aprikose- Erdbeer, Dose, 0,25 l",
    "Red Bull White Edition Kokos Blaubeere, Dose, 0,25 l",
    "Red Bull Yellow Edition Tropical, Dose, 0,25 l",
    "Red Bull Zero Energy Drink, Dose, 0,25 l",
    "Reign Lemon, Dose, 0,50 l",
    "Reign Melone Mania, Dose, 0,50 l",
    "Rockstar Super Sours Energy Drink Green Apple, Dose, 0,50 l",
    "Rockstar Super Sours Energy Blue Raspberry, Dose, 0,50 l",
    "Rockstar Energy Punched Guave, Dose, 0,50 l",
    "Rockstar Energy Juiced Mango Orange, Dose, 0,50 l",
    "Rockstar Energy Original, Dose, 0,50 l",
    "Rockstar Energy Drink Original, Dose, 0,25 l",
    "Take Off Classic Energy, Dose, 0,5 l",
    "Rockstar Energy Drink Punched Tropical Guava, Dose, 0,25 l",
    "Rockstar XD Waldmeister Boost, Dose, 0,50 l",
    "Rockstar Energy Drink XDurance Blueberry, Dose, 0,25 l",
    "Rockstar Energy XDurance Blueberry, Dose, 0,50 l",
    "Silberpfeil Black Orange, Dose, 0,25 l",
    "Silberpfeil Classic Energy Drink, Dose, 0,25 l",
    "Silberpfeil Sugar Free, Dose, 0,25 l",
    "Silberpfeil Watermelon, Dose, 0,25 l",
    "Spezi e:nergy, Dose, 0,33 l",
    "Take Off Energy Drink Classic, Dose, 0,50 l",
    "Take Off Energy Drink, Dose, 0,33 l",
    "Take Off Jungle Maniac - Mango Maracuja, Dose, 0,50 l",
    "Take Off Jungle Maniac - Mango Maracuja, Dose, 0,5 l",
    "Take Off Space Cat - Berry Marshmallow, Dose, 0,5 l",
    "Take Off Space Cat - Berry Marshmallow, Dose, 0,50 l",
    "Take Off Wassermelone, Dose, 0,33 l",
    "Take Off Zero, Dose, 0,33 l",
    "Take Off Zombie Attack - Blood Orange Lemon, Dose, 0,50 l",
    "Vita Energy Rote Traube-Acai Sleek-Dose, Dose, 0,33 l",
    "X15 Energy, Flasche, 1,50 l",
    "X15 Energy Drink, Dose, 0,25 l",
    "Monster Energy Mixdisplay 4-fach sortiert, Dose, 0,50 l",
    "Red Bull Energy Drink Display Dolly, Dose, 0,25 l",
    "Rockstar Energy Drink Mixdisplay 4-fach sortiert, Dose, 0,50 l",
    "Organics by Red Bull Orange BIO, Dose, 0,25 l",
    "Organics by Red Bull Viva Mate, Dose, 0,25 l",
    "Schweppes American Ginger Ale, Flasche, 1,25 l",
    "Adelholzener Miwa Classic Sportslock, Flasche, 0,75 l",
    "Gerolsteiner Sprudel, Flasche, 0,75 l",
    "hella classic, Flasche, 0,75 l",
    "hella classic, Flasche, 1,50 l",
    "Untouched National Park Water Sparkling, Flasche, 0,50 l",
    "Untouched National Park Water Sparkling, Flasche, 0,75 l",
    "Vöslauer Mineralwasser prickelnd, Flasche, 1,00 l",
    "Vöslauer Mineralwasser prickelnd, Flasche, 1,50 l",
    "Adelholzener Mineralwasser Sanft, Flasche, 0,50 l",
    "Adelholzener Mineralwasser Sanft, Flasche, 1,00 l",
    "Gerolsteiner Medium, Flasche, 0,75 l",
    "hella medium, Flasche, 0,75 l",
    "hella medium, Flasche, 1,50 l",
    "Rheinfels Quelle Medium, Flasche, 0,50 l",
    "Santa Emilia Wasser mit Kohlensäure 4x6er, Flasche, 0,50 l",
    "Santa Emilia Wasser mit Kohlensäure, Flasche, 1,50 l",
    "share Mineralwasser medium, Flasche, 0,50 l",
    "Volvic Mediumperlig, Flasche, 0,45 l",
    "Christinen Carat Naturelle, PET-Flasche, 0,50 l",
    "Acqua Panna Mineralwasser, Flasche, 1,00 l",
    "Adelholzener Miwa Naturell Sportslock, Flasche, 0,75 l",
    "Adelholzener Mineralwasser Naturell, Flasche, 1,00 l",
    "Evian Go Sportscap, Flasche, 0,75 l",
    "Evian Premium, Flasche, 1,50 l",
    "Fürst Bismarck Wellness, Flasche, 0,50 l",
    "Gerolsteiner Naturell, Flasche, 0,75 l",
    "Gerolsteiner Naturell, Flasche, 1,50 l",
    "hella naturell, Flasche, 0,75 l",
    "hella naturell, Flasche, 1,50 l",
    "Untouched National Park Water Still, Flasche, 0,50 l",
    "Untouched National Park Water Still, Flasche, 0,75 l",
    "Santa Emilia Wasser ohne Kohlensäure 4x6er, Flasche, 0,50 l",
    "Santa Emilia Wasser ohne Kohlensäure, Flasche, 1,50 l",
    "share MiWa still, Flasche, 0,50 l",
    "Volvic Naturelle, Flasche, 1,50 l",
    "Vöslauer Mineralwasser ohne, Flasche, 1,00 l",
    "Vöslauer Mineralwasser ohne, Flasche, 1,50 l",
    "Active O2 Apfel Kiwi, Flasche, 0,75 l",
    "Active O2 Bio Apfel, Flasche, 0,75 l",
    "Active O2 Cherry, Flasche, 0,75 l",
    "Active O2 Himbeer Cranberry, Flasche, 0,75 l",
    "Active O2 Iced Berry, Flasche, 0,75 l",
    "Active O2 Lemon, Flasche, 0,75 l",
    "Active O2 Lemon Iced Tea, Flasche, 0,75 l",
    "Active O2 Lime Ice, Flasche, 0,75 l",
    "Active O2 Iced Passion Lime, Flasche, 0,75 l",
    "Active O2 Orange Lemon, Flasche, 0,75 l",
    "Active O2 Bio Orange, Flasche, 0,75 l",
    "Active O2 Iced Peach, Flasche, 0,75 l",
    "Adelholzener Mango, Flasche, 0,50 l",
    "Gerolsteiner Leichte Schorle Apfel- Zitrone, Flasche, 0,75 l",
    "Gerolsteiner Fruity Zitrone PET, Flasche, 0,75 l",
    "Gerolsteiner Fruity Beere, Flasche, 0,75 l",
    "Get More Vits Multivits Zitrone Limette Spritzig, Flasche, 0,50 l",
    "Get More Vits Vitamin D Mango \u0026 Passionsfrucht still, Flasche, 0,50 l",
    "Get More Vits Vitamin C Orange Spritzig, Flasche, 0,50 l",
    "hella near water erdbeere, Flasche, 0,75 l",
    "hella near water himbeere, Flasche, 0,75 l",
    "hella near water johannisbeer, Flasche, 0,75 l",
    "hella near water kirsche, Flasche, 0,75 l",
    "hella near water mango picchu, Flasche, 0,75 l",
    "Hella Near Water holunderbrise, Flasche, 0,75 l",
    "Hella Near Water pink caribic, Flasche, 0,75 l",
    "Hella Near Water wassermelone, Flasche, 0,75 l",
    "hella near water birne, Flasche, 1,50 l",
    "hella near water erdbeere, Flasche, 1,50 l",
    "hella near water himbeere, Flasche, 1,50 l",
    "hella near water kirsche, Flasche, 1,50 l",
    "Untouched Bio-Apfelschorle, Flasche, 0,50 l",
    "Untouched Bio-Rhababerschorle, Flasche, 0,50 l",
    "Hohes C Functional Water Antiox, Flasche, 0,75 l",
    "Hohes C Functional Water Boost, Flasche, 0,75 l",
    "Hohes C Functional Water Energy, Flasche, 0,75 l",
    "Hohes C Functional Water Immun, Flasche, 0,75 l",
    "Hohes C Functional Water Mind, Flasche, 0,75 l",
    "Lichtenauer Fresh \u0026 Fruity Himbeere, Flasche, 0,75 l",
    "Rheinfels Quelle Lemon, Flasche, 0,75 l",
    "Rheinfels Quelle Limette-Minze, Flasche, 0,75 l",
    "Rheinfels Quelle Grapefrucht, Flasche, 0,75 l",
    "Vilsa H2 Obst Iso Grape, Flasche, 0,75 l",
    "Vilsa H2 Obst Orange, Flasche, 0,75 l",
    "Vilsa H2 Obst Waldbeere, Flasche, 0,75 l",
    "Vitamin Well Hydrate, Flasche, 0,50 l",
    "Vitamin Well Recover, Flasche, 0,50 l",
    "Vitamin Well Reload, Flasche, 0,50 l",
    "Volvic Essence BIO Apfel Zitrone, Flasche, 0,75 l",
    "Volvic Essence BIO Apfel-Zitrone, Flasche, 1,25 l",
    "Volvic Essence BIO Minze Gurke, Flasche, 0,75 l",
    "Volvic Essence BIO Minze-Gurke, Flasche, 1,25 l",
    "Volvic Essence BIO Orange- Holunderblüte, Flasche, 0,75 l",
    "Volvic Essence BIO Orange- Holunderblüte, Flasche, 1,25 l",
    "Volvic Essence BIO Zitrusfrucht- Rosmarin, Flasche, 0,75 l",
    "Volvic Touch Apfel, Flasche, 0,75 l",
    "Volvic Touch Kirsche, Flasche, 0,75 l",
    "Volvic Touch Rote Früchte, Flasche, 0,75 l",
    "Volvic Touch Zitrone Limette, Flasche, 0,75 l",
    "Vöslauer Mineralwasser Flavour Himbeere, Flasche, 0,50 l",
    "Vöslauer Mineralwasser Flavour Zitrone, Flasche, 0,50 l",
    "Vöslauer Balance Pink Grapefruit, Flasche, 0,75 l",
    "Vöslauer Flavour Himbeere, Flasche, 1,00 l",
    "Vöslauer Flavour Lemongrass, Flasche, 1,00 l",
    "Vöslauer Flavour Mango, Flasche, 1,00 l",
    "Vöslauer Flavour Zitrone, Flasche, 1,00 l",
    "Ahoj Brause Himbeere, Dose, 0,33 l",
    "Ahoj Brause Waldmeister, Dose, 0,33 l",
    "ALGE Limette Softdrink mit Guarana, Dose, 0,33 l",
    "Coca Cola Movement Limited Edition Flavour Zero Sugar, Dose, 0,25 l",
    "Coca Cola Alu Dose, Dose, 0,33 l",
    "Coca Cola Cherry Alu Dose, Dose, 0,33 l",
    "Coca Cola Zero Alu Dose, Dose, 0,33 l",
    "Coca Cola Zero Lemon, Flasche, 0,50 l",
    "Dr. Pepper, Dose, 0,33 l",
    "Fanta Exotic Alu Sleek Can, Dose, 0,33 l",
    "Fanta Lemon, Dose, 0,33 l",
    "Fanta Mango Dragon Alu Sleek Can, Dose, 0,33 l",
    "Fanta Orange Alu Dose, Dose, 0,33 l",
    "Fanta Strawberry \u0026 Kiwi Alu Sleek Can, Dose, 0,33 l",
    "Fanta Lemon, Flasche, 0,50 l",
    "Gerolsteiner Leichte Limo Citrus- Minze, Flasche, 0,75 l",
    "Gerolsteiner Leichte Limo Orange- Passionsfrucht, Flasche, 0,75 l",
    "Gerolsteiner Orangen-Limonade, Flasche, 0,75 l",
    "Gerolsteiner Zitronen-Limonade, Flasche, 0,75 l",
    "Granini Die Limo Ultraleicht Orange, Flasche, 1,00 l",
    "Granini Die Limo Ultraleicht Zitrone, Flasche, 1,00 l",
    "Crodo Lemon Soda, Dose, 0,33 l",
    "LevlUp Hydration Drink Galaxy, Flasche, 0,50 l",
    "LevlUp Hydration Drink Nuke, Flasche, 0,50 l",
    "LevlUp Hydration Drink Shiny Dragon, Flasche, 0,50 l",
    "Lombi Cola Classic, Dose, 0,33 l",
    "Lombi Cola Zero, Dose, 0,33 l",
    "Mezzo Mix Orange Alu Dose, Dose, 0,33 l",
    "Mezzo Mix Orange, Flasche, 0,50 l",
    "Moloko - Erfrischungsgetränk, Dose, 0,25 l",
    "Mountain Dew Regular, Flasche, 0,50 l",
    "Crodo Oran Soda, Dose, 0,33 l",
    "Paulaner Spezi, Dose, 0,33 l",
    "Paulaner Spezi Zero, Dose, 0,33 l",
    "Pepsi Cola, Dose, 0,33 l",
    "Pepsi Zero Zucker, Dose, 0,33 l",
    "Pepsi Cola, Flasche, 0,50 l",
    "Pepsi Zero Zucker, Flasche, 0,50 l",
    "Raak Kinder Cola, Flasche, 0,25 l",
    "Organics by Red Bull Simply Cola, Dose, 0,25 l",
    "Sanpellegrino Naturali Aranciata, Dose, 0,33 l",
    "Sanpellegrino Naturali Clementina, Dose, 0,33 l",
    "Sanpellegrino Creazioni Blutorange \u0026 Orangenblüte, Dose, 0,33 l",
    "Sanpellegrino Creazioni Granatapfel \u0026 schwarze Johannisbeere, Dose, 0,33 l",
    "Sanpellegrino Naturali Limone e Menta, Dose, 0,33 l",
    "Sanpellegrino Naturali Limonata, Dose, 0,33 l",
    "Sanpellegrino Naturali Melograno, Dose, 0,33 l",
    "Sanpellegrino Naturali Pompelmo, Dose, 0,33 l",
    "Sanpellegrino Naturali Aranciata Rossa, Dose, 0,33 l",
    "Schwip Schwap, Flasche, 0,50 l",
    "Sinalco Orange, Flasche, 1,25 l",
    "Sinconade Granatapfel Preiselbeere, Flasche, 0,50 l",
    "Sprite Aludose, Dose, 0,33 l",
    "Sunkist Fruit Mix, Dose, 0,33 l",
    "Sunkist Orange, Dose, 0,33 l",
    "Sunkist Pomegranate, Dose, 0,33 l",
    "Sunkist Watermelon, Dose, 0,33 l",
    "Uludag Gazoz, Dose, 0,33 l",
    "Vilsa Leichte Limo Blaubeere BIO, Flasche, 0,75 l",
    "Vilsa Leichte Limo Orange- Maracuja BIO, Flasche, 0,75 l",
    "Vilsa Leichte Limo Rhabarber BIO, Flasche, 0,75 l",
    "Vilsa Leichte Limo Trübe Zitrone, Flasche, 0,75 l",
    "VIO Limetten-Minz, Flasche, 1,00 l",
    "VIO Zitrus, Flasche, 1,00 l",
    "Capri Sun Kirsch, PET-Flasche, 0,20 l",
    "Capri Sun Multivitamin, PET-Flasche, 0,20 l",
    "Capri Sun Orange, PET-Flasche, 0,20 l",
    "Capri Sun Kirsche-Granatapfel, PET-Flasche, 0,33 l",
    "Capri Sun Multivitamin, PET-Flasche, 0,33 l",
    "Capri Sun Orange Peach, PET-Flasche, 0,33 l",
    "QuickVit Durstlöscher Apfel/ Orange/Zitrone, PET-Flasche, 0,50 l",
    "QuickVit Durstlöscher Blaubeere- Vanille, PET-Flasche, 0,50 l",
    "QuickVit Durstlöscher Bubble Gum, PET-Flasche, 0,50 l",
    "QuickVit Durstlöscher Cola, PET-Flasche, 0,50 l",
    "QuickVit Durstlöscher Granatapfel- Zitrone, PET-Flasche, 0,50 l",
    "QuickVit Durstlöscher:in Regenbogen Edition, PET-Flasche, 0,5 l",
    "QuickVit Durstlöscher KIBA, PET-Flasche, 0,50 l",
    "QuickVit Durstlöscher Kirsch/ Zitrone, PET-Flasche, 0,50 l",
    "QuickVit Durstlöscher Multivitamin, PET-Flasche, 0,50 l",
    "QuickVit Durstlöscher Orange, PET-Flasche, 0,50 l",
    "QuickVit Durstlöscher:in Regenbogen, PET-Flasche, 0,50 l",
    "QuickVit Durstlöscher Saurer Apfel, PET-Flasche, 0,50 l",
    "QuickVit Durstlöscher Waldmeister, PET-Flasche, 0,50 l",
    "QuickVit Durstlöscher Wassermelone, PET-Flasche, 0,50 l",
    "QuickVit Durstlöscher Zuckerwatte, PET-Flasche, 0,50 l",
    "Tymbark Apfel- Wassermelonengetränk, PET-Flasche, 0,50 l",
    "Tymbark Mango-Apfel-Orange, PET-Flasche, 0,50 l",
    "Active Fresh Kirsche Zitrone, Flasche, 0,75 l",
    "Active Fresh Orange Sternfrucht, Flasche, 0,75 l",
    "Active Fresh Orange Maracuja, Flasche, 0,75 l",
    "Culinary Limette 100%, Flasche, 1,00 l",
    "Frucht Tiger Apfel-Erdbeere, Flasche, 0,50 l",
    "Frucht Tiger Multifrucht, Flasche, 0,50 l",
    "Frucht Tiger Orange-Maracuja, Flasche, 0,50 l",
    "Gerolsteiner Leichte Schorle Apfel- Kirsche, Flasche, 0,75 l",
    "Granini Selection Maracuja, Flasche, 0,75 l",
    "Granini Select Guave- Drachenfrucht, Flasche, 0,75 l",
    "granini Trinkgenuss Apfel trüb, Flasche, 1,00 l",
    "granini Trinkgenuss Apfel-Kirsch, Flasche, 1,00 l",
    "granini Trinkgenuss Banane, Flasche, 1,00 l",
    "granini Trinkgenuss Multivitamin 50% Fruchtgehalt, Flasche, 1,00 l",
    "granini Trinkgenuss Orange Mango, Flasche, 1,00 l",
    "granini Trinkgenuss Orangensaft, Flasche, 1,00 l",
    "hella ACE, Flasche, 0,75 l",
    "Hohes C Super Shot Antiox, Dose, 0,33 l",
    "Hohes C Super Shot Bauchgefühl, Dose, 0,33 l",
    "Hohes C Super Shot Energie, Dose, 0,33 l",
    "Hohes C Super Shot Immun, Dose, 0,33 l",
    "hohes C Apfelsaft, Flasche, 0,50 l",
    "hohes C Milde Orange, Flasche, 0,50 l",
    "hohes C Multivitamin, Flasche, 0,50 l",
    "hohes C Orange, Flasche, 0,50 l",
    "hohes C Immun, Flasche, 1,00 l",
    "hohes C Fokus, Flasche, 1,00 l",
    "hohes C Mildes Frühstück, Flasche, 1,00 l",
    "hohes C Milder Multi, Flasche, 1,00 l",
    "hohes C Milde Orange, Flasche, 1,00 l",
    "hohes C Milder Apfel, Flasche, 1,00 l",
    "hohes C Multivitamin, Flasche, 1,00 l",
    "hohes C Orange, Flasche, 1,00 l",
    "hohes C Plus Eisen, Flasche, 1,00 l",
    "hohes C Plus Sonnenvitamin D, Flasche, 1,00 l",
    "hohes C Roter Multivitaminsaft, Flasche, 1,00 l",
    "WeserGold Apfelsaft, Flasche, 0,33 l",
    "WeserGold Milder Apfelsaft, Flasche, 1,00 l",
    "WeserGold Milder Orangensaft, Flasche, 1,00 l",
    "WeserGold Orangensaft, Flasche, 0,33 l",
    "Yippy Erdbeere, Flasche, 0,33 l",
    "Vitavate Grüner Apfel, Flasche, 0,50 l",
    "Vitavate Himbeere, Flasche, 0,50 l",
    "Amecke Bio Sanfte Säfte Apfel Aprikose, PET-Flasche, 1,00 l",
    "Amecke Bio Sanfte Säfte Apfel pur, PET-Flasche, 1,00 l",
    "Amecke Bio Sanfte Säfte Orange Yuzu, PET-Flasche, 1,00 l",
    "Amecke Bio Sanfte Orange, PET-Flasche, 1,00 l",
    "Amecke Sanfte Säfte Apfel klar, PET-Flasche, 1,00 l",
    "Amecke Sanfte Säfte Madarine- Orange, PET-Flasche, 1,00 l",
    "Amecke Sanfte Säfte Multivitamin, PET-Flasche, 1,00 l",
    "Amecke Sanfte Säfte Orange, PET-Flasche, 1,00 l",
    "Amecke Sanfte Säfte Pink Grapefruit-Apfel-Sweetie, PET-Flasche, 1,00 l",
    "beckers bester Apfelsaft klar 100% Direktsaft, PET-Flasche, 1,00 l",
    "beckers bester Apfelsaft trüb 100% Direktsaft, PET-Flasche, 1,00 l",
    "beckers bester Bananen-Nektar mit Direktsaft, PET-Flasche, 1,00 l",
    "beckers bester Cranberry-Nektar mit Direktsaft, PET-Flasche, 1,00 l",
    "beckers bester Frühstückssaft 100% Direktsaft, PET-Flasche, 1,00 l",
    "beckers bester Schwarzer Johannisbeer-Nektar mit Direktsaft, PET-Flasche, 1,00 l",
    "beckers bester Kirsch-Nektar mit Direktsaft, PET-Flasche, 1,00 l",
    "beckers bester Mango-Nektar mit Direktsaft, PET-Flasche, 1,00 l",
    "beckers bester Marcuja-Nektar mit Direktsaft, PET-Flasche, 1,00 l",
    "beckers bester Multisaft 100% Direktsaft, PET-Flasche, 1,00 l",
    "beckers bester Orangensaft 100% Direktsaft, PET-Flasche, 1,00 l",
    "beckers bester Rhabarber-Nektar mit Direktsaft, PET-Flasche, 1,00 l",
    "beckers bester roter Traubensaft 100% Direktsaft, PET-Flasche, 1,00 l",
    "beckers bester weißer Traubensaft 100% Direktsaft, PET-Flasche, 1,00 l",
    "Christinen Fruit Drink Apfel- Orange-Zitrone, PET-Flasche, 0,50 l",
    "Christinen Fruit Drink Apfel-Birne, PET-Flasche, 0,50 l",
    "Christinen Fruit Drink Apfel-Cassis, PET-Flasche, 0,50 l",
    "Christinen Fruit Drink Multi- Vitamin, PET-Flasche, 0,50 l",
    "happy day Ananassaft 100%, PET-Flasche, 1,00 l",
    "Happy Day Apfel Mild, PET-Flasche, 1,00 l",
    "Happy Day Apfel naturtrüb, PET-Flasche, 1,00 l",
    "happy day Banane, PET-Flasche, 1,00 l",
    "Happy Day Birnennektar, PET-Flasche, 1,00 l",
    "Happy Day Cocos Ananas, PET-Flasche, 1,00 l",
    "happy day Cranberry, PET-Flasche, 1,00 l",
    "Happy Day Drachenfrucht, PET-Flasche, 1,00 l",
    "happy day Erdbeere, PET-Flasche, 1,00 l",
    "happy day Granatapfel, PET-Flasche, 1,00 l",
    "happy day Kirsche / Cherry, PET-Flasche, 1,00 l",
    "happy day Mango, PET-Flasche, 1,00 l",
    "happy day Maracuja, PET-Flasche, 1,00 l",
    "Happy Day Multivitamin Mild, PET-Flasche, 1,00 l",
    "Happy Day Orange Mango, PET-Flasche, 1,00 l",
    "Happy Day Orange Maracuja, PET-Flasche, 1,00 l",
    "Happy Day Pink Grapefruit, PET-Flasche, 1,00 l",
    "happy day Rhabarber, PET-Flasche, 1,00 l",
    "Happy Day Rote Traube, PET-Flasche, 1,00 l",
    "Happy Day Schwarzer Johannisbeernektar, PET-Flasche, 1,00 l",
    "Happy Day Tomate 100%, PET-Flasche, 1,00 l",
    "Pfanner Maracuja Getränk 15% Fruchtgehalt, PET-Flasche, 1,00 l",
    "Pfanner Multivitaminsaft 100% Fruchtgehalt, PET-Flasche, 1,00 l",
    "Pfanner Orangensaft 100%, PET-Flasche, 1,00 l",
    "Pfanner Schwarzer Johannisbeer Nektar 25% Fruchtgehalt, PET-Flasche, 1,00 l",
    "Pfanner Apfelsaft 100%, PET-Flasche, 2,00 l",
    "Pfanner Orangensaft 100%, PET-Flasche, 2,00 l",
    "Rauch Multivitamin 100%, Flasche, 0,20 l",
    "Rauch Orange 100% BIO, Flasche, 0,20 l",
    "Rotbäckchen Morgenstark, Flasche, 0,70 l",
    "Rotbäckchen Lernstark, Flasche, 0,70 l",
    "Rotbäckchen Immunstark, Flasche, 0,70 l",
    "Rotbäckchen Sonnenkraft, Flasche, 0,70 l",
    "Rotbäckchen Das Original, Flasche, 0,70 l",
    "WeserGold Gemüsesaft, PET-Flasche, 1,00 l",
    "WeserGold Tomatensaft, PET-Flasche, 1,00 l",
    "WeserGold Apfelsaft, PET-Flasche, 1,00 l",
    "WeserGold Orangensaft, PET-Flasche, 1,0 l",
    "WeserGold Zitronensaft, PET-Flasche, 1,00 l",
    "Robby Bubble Berry, Flasche, 0,75 l",
    "Robby Bubble Apple Cherry, Flasche, 0,75 l",
    "Robby Bubble Jungle Party, Flasche, 0,75 l",
    "Sangrita Classico, Flasche, 0,50 l",
    "Sangrita Picante, Flasche, 0,50 l"
];

window.DEFAULT_CIGARETTE_CATALOG = [
  "Marlboro Red, 20er Original Pack",
  "Marlboro Red, XL / 2XL, ca. 22-28 Stück",
  "Marlboro Red, 9XL / Big Pack, ca. 40+ Stück",
  "Marlboro Red Long, 100 mm / Long, 20er",
  "Marlboro Gold, 20er Original Pack",
  "Marlboro Gold, XL / 2XL, ca. 22-28 Stück",
  "Marlboro Gold, Big Pack, ca. 40+ Stück",
  "Marlboro Gold Long, 100 mm / Long, 20er",
  "Marlboro Crafted Red, 20er",
  "Marlboro Crafted Gold, 20er",
  "Marlboro Silver / Fine Touch, 20er, eher optional",
  "Marlboro Mix / Mix XL, XL / Großpackung, optional",
  "Camel Yellow, 20er",
  "Camel Yellow, XL / Big Pack, ca. 24-30 Stück",
  "Camel Yellow, 6XL / Großpackung, ca. 50+ Stück",
  "Camel Blue, 20er",
  "Camel Blue, XL / Big Pack, ca. 24-30 Stück",
  "Camel Blue, 6XL / Großpackung, ca. 50+ Stück",
  "Camel Activate / Capsule-Nachfolger, falls geführt, 20er, optional",
  "Lucky Strike Red, 20er",
  "Lucky Strike Red, Giga / XL, ca. 22-24 Stück",
  "Lucky Strike Blue / ehemals Amber, 20er",
  "Lucky Strike Blue, Giga / XL, ca. 22-24 Stück",
  "Lucky Strike Authentic Red, 20er",
  "Lucky Strike Authentic Red, Giga / XL, ca. 22 Stück",
  "Lucky Strike Authentic Blue, 20er, optional",
  "Lucky Strike Crafted Red, 20er, optional",
  "Lucky Strike Crafted Gold / Blue, 20er, optional",
  "Pall Mall Red, 20er",
  "Pall Mall Red, XL / Big Pack, ca. 24-30 Stück",
  "Pall Mall Red, Giga / Großpackung, ca. 38-40 Stück",
  "Pall Mall Blue, 20er",
  "Pall Mall Blue, XL / Big Pack, ca. 24-30 Stück",
  "Pall Mall Blue, Giga / Großpackung, ca. 38-40 Stück",
  "Pall Mall Red Flow / Shift-Nachfolger, falls geführt, 20er, optional",
  "Pall Mall Ohne Zusätze / Natural, 20er, optional",
  "L&M Red Label, 20er",
  "L&M Red Label, Giga / XL, ca. 24-26 Stück",
  "L&M Blue Label, 20er",
  "L&M Blue Label, Giga / XL, ca. 24-26 Stück",
  "L&M Forward / Spezialfilter, falls geführt, 20er, optional",
  "Winston Red, 20er",
  "Winston Red, Big Pack / XL, ca. 22-24 Stück",
  "Winston Blue, 20er",
  "Winston Blue, Big Pack / XL, ca. 22-24 Stück",
  "Winston Black, 20er, optional",
  "Winston Silver, 20er, optional",
  "Chesterfield Original / Red, 20er",
  "Chesterfield Red, 26er / 2XL",
  "Chesterfield Red, 30er / 2XL",
  "Chesterfield Blue, 20er",
  "Chesterfield Blue, 26er",
  "Chesterfield Blue, 30er / 2XL",
  "Chesterfield Blue, 38er / 4XL",
  "Chesterfield True Blue / ohne Zusätze, 20er, optional",
  "Chesterfield True Red / ohne Zusätze, 20er, optional",
  "JPS / John Player Special Red, 20er",
  "JPS Red, XL / Big Pack, ca. 24-27 Stück",
  "JPS Blue, 20er",
  "JPS Blue, XL / Big Pack, ca. 24-27 Stück",
  "JPS Black, 20er, optional",
  "JPS Silver, 20er, optional",
  "West Original / Red, 20er",
  "West Red, XL / Big Pack, ca. 24-30 Stück",
  "West Silver, 20er",
  "West Silver, XL / 6XL, ca. 30-40 Stück",
  "West Blue, 20er, optional",
  "West Ice / Spezialfilter, falls geführt, 20er, optional",
  "Gauloises Blondes Blau, 20er",
  "Gauloises Blondes Blau, XL / Großpackung, ca. 22-30 Stück",
  "Gauloises Blondes Rot, 20er",
  "Gauloises Blondes Rot, XL / Großpackung, ca. 22-30 Stück",
  "Gauloises Gold, 20er / 22er, optional",
  "Gauloises Brunes Plain Filtre, 20er, eher selten",
  "Davidoff Classic, 20er",
  "Davidoff Gold, 20er",
  "Davidoff Silver, 20er",
  "Davidoff Magnum / größere Packung, optional",
  "HB Classic Blend, Big Pack / BP, ca. 22 Stück",
  "HB Classic Blend 100, 100 mm / Long, 20er",
  "HB Rounded Blend, King Size, 20er",
  "Parliament Night Blue, 100 mm / Long, 20er",
  "Parliament Aqua Blue, 20er / 100 mm, optional",
  "Peter Stuyvesant Original, 20er",
  "Peter Stuyvesant Big Box, Big Pack, ca. 20-25 Stück",
  "Peter Stuyvesant 100, 100 mm / Long, 20er",
  "Peter Stuyvesant Gold, 20er, optional",
  "Peter Stuyvesant Silver, 20er, optional",
  "Lord Extra, Big Pack / ca. 22 Stück",
  "Lord Extra 100, 100 mm / Long, 20er",
  "Lord Blue 100, 100 mm / Long, 20er",
  "Denim Red, 20er",
  "Denim Red, XL, ca. 25 Stück",
  "Denim Red, XXL, ca. 29 Stück",
  "Denim Red, XXXL / UP, ca. 40 Stück",
  "Denim Red Duo Pack, ca. 60 Stück",
  "Denim Blue, 20er",
  "Denim Blue, XL, ca. 25 Stück",
  "Denim Blue, 3XL / Großpackung, ca. 40 Stück",
  "Burton Original / Red, 20er",
  "Burton Original / Red, XL, ca. 24 Stück",
  "Burton Original / Red, XXL, ca. 29 Stück",
  "Burton Original / Red, XXXL, ca. 40 Stück",
  "Burton Original / Red 5XL / Duo, ca. 60 Stück",
  "Burton Blue, 20er",
  "Burton Blue, XL, ca. 24 Stück",
  "Burton Blue, XXL, ca. 29 Stück",
  "Burton Blue, XXXL, ca. 40 Stück",
  "Elixyr Red, 20er",
  "Elixyr Red, XL, ca. 25 Stück",
  "Elixyr Red, XXL, ca. 29 Stück",
  "Elixyr Red, XXXXL, ca. 39 Stück",
  "Elixyr Red 5XL, ca. 49 Stück",
  "Elixyr Blue, XL, ca. 25 Stück",
  "Elixyr Blue, XXL, ca. 29 Stück",
  "Elixyr+ M-Type Green, 20er / 24er / 27er",
  "Elixyr+ X-Type Blue, 24er",
  "Paramount Red, 20er",
  "Paramount Red, 30er",
  "Paramount Red, 34er, optional",
  "Paramount Red, 52er, optional",
  "Paramount Blue, 20er",
  "Paramount Blue, 30er / 34er / 52er, optional",
  "R1 Blue / Slim Line, 20er",
  "R1 Red, 20er",
  "R1 Minima / Super Slim, 20er, optional",
  "Vogue Bleue, Slim, 20er",
  "Vogue Lilas, Slim, 20er",
  "Vogue Caractère, Slim, 20er",
  "F6 Original, 20er",
  "F6 Original, 30er / 2XL",
  "F6 Blue / Silver, 20er, optional",
  "Fair Play Red, 20er",
  "Fair Play Red, XL / Big Pack",
  "Fair Play Blue, 20er, optional",
  "American Spirit Blue, 20er",
  "American Spirit Yellow, 20er",
  "American Spirit Orange / Organic, 20er, optional",
  "Pueblo Classic / Beige, 20er",
  "Pueblo Blue, 20er",
  "Pueblo Orange, 20er, optional",
  "Ernte 23 Original, 20er, optional",
  "R6 Red / Classic, 20er, optional",
  "Reval Filter, 20er, selten",
  "Roth-Händle Filter, 20er, selten",
  "Dunhill International Red, 20er, Premium/selten",
  "Dunhill Blue, 20er, Premium/selten",
  "Benson & Hedges Gold, 20er, optional",
  "Gitanes Blondes, 20er, selten",
  "Pepe Rich Green / Dark Green, 20er, optional",
  "Pepe Bright Green, 20er, optional",
  "Manitou Organic / ohne Zusätze, 20er, optional",
  "Mark Adams No.1 Red / Blue, 20er, optional",
  "Tawa Red, XL / XXL, optional",
  "Tawa Silver, XL, optional",
  "Woodland Craft / Wood Filter, 20er, optional",
  "Las Vegas Red, 20er / Großpackung, optional",
  "Ducal Red, 25er / 29er, optional",
  "Prince Rich, 20er, optional",
  "Allure Organic / Superslim, 20er / 40er, optional"
];

window.LEGACY_CIGARETTE_CATALOG = window.DEFAULT_CIGARETTE_CATALOG;

window.DEFAULT_CIGARETTE_CATALOG = [
  "Marlboro|Red|L, XL, 2XL, 4XL, 7XL, 9XL",
  "Marlboro|Gold|L, XL, 2XL, 4XL, 7XL",
  "Marlboro|Red Long|L",
  "Marlboro|Gold Long|L",
  "Marlboro|Crafted Red|L, 2XL, 7XL",
  "Marlboro|Crafted Gold|L, 2XL, 7XL",
  "Marlboro|Simply Red|L",
  "Marlboro|Simply Gold|L",
  "Marlboro|Mix|L, XL, 2XL",
  "Marlboro|Silver / Fine Touch|L",
  "Camel|Yellow|L, 2XL, 6XL",
  "Camel|Blue|L, 2XL, 6XL",
  "Camel|Yellow Long|L, 2XL",
  "Camel|Yellow ohne Filter|L",
  "Lucky Strike|Red|L, 2XL, 3XL, 6XL",
  "Lucky Strike|Blue|L, 2XL, 3XL, 6XL",
  "Lucky Strike|Authentic Red|L, 2XL, 3XL",
  "Lucky Strike|Authentic Blue|L, 2XL, 3XL",
  "Lucky Strike|Crafted Red|L, XL, 6XL",
  "Lucky Strike|Crafted Blue|L, XL, 6XL",
  "Lucky Strike|Ohne Filter|L",
  "Pall Mall|Red|L, XL, 2XL, 5XL",
  "Pall Mall|Blue|L, XL, 2XL, 5XL",
  "Pall Mall|Authentic Red|L, XL",
  "Pall Mall|Authentic Blue|L, XL",
  "Pall Mall|Flow Red|L",
  "Pall Mall|Flow Blue|L",
  "Pall Mall|Natural / ohne Zusätze|L",
  "L&M|Red Label|L, XL, 2XL, 4XL, 7XL, 9XL",
  "L&M|Blue Label|L, XL, 2XL, 4XL, 7XL",
  "L&M|Simply Red|L",
  "L&M|Simply Blue|L",
  "L&M|Red Long|L",
  "L&M|Blue Long|L",
  "Winston|Red|L, 2XL, 5XL, 6XL",
  "Winston|Blue|L, 2XL, 6XL",
  "Winston|Black|L",
  "Winston|Silver|L",
  "Winston|Red Long|L, 2XL",
  "Chesterfield|Original / Red|L, XL, 2XL, 4XL",
  "Chesterfield|Blue|L, XL, 2XL, 4XL",
  "Chesterfield|True Red|L",
  "Chesterfield|True Blue|L",
  "Chesterfield|Ohne Filter / Unplugged|L",
  "JPS / John Player Special|Red|L, XL, 2XL, 3XL, 4XL, 5XL",
  "JPS|Blue|L, XL, 2XL, 3XL, 4XL, 5XL",
  "JPS|Black|L",
  "JPS|Silver|L",
  "JPS|Just Red|L, 2XL",
  "JPS|Just Blue|L, 2XL",
  "JPS|Slims|L",
  "West|Original Red|L, XL, 2XL, 3XL, 4XL, 5XL",
  "West|Silver|L, 2XL, 4XL, 5XL",
  "West|Blue|L",
  "West|Polar / Ice|L",
  "West|Red Long|L",
  "West|Silver Long|L",
  "Gauloises|Blondes Blau|L, XL, 3XL, 6XL",
  "Gauloises|Blondes Rot|L, XL, 3XL, 6XL",
  "Gauloises|Gold|L, XL",
  "Gauloises|Brunes|L",
  "Davidoff|Classic|L",
  "Davidoff|Gold|L, 2XL",
  "Davidoff|Silver|L",
  "Davidoff|Gold Slim|L",
  "Davidoff|Magnum|L",
  "HB|Classic Blend|L, XL",
  "HB|Classic Blend 100 / Long|L",
  "HB|Rounded Blend|L",
  "Parliament|Night Blue|L",
  "Parliament|Night Blue Long|L",
  "Parliament|Aqua Blue|L",
  "Peter Stuyvesant|Original|L, XL",
  "Peter Stuyvesant|Big Box|XL",
  "Peter Stuyvesant|100 / Long|L",
  "Peter Stuyvesant|Gold|L",
  "Peter Stuyvesant|Silver|L",
  "Lord|Extra|XL",
  "Lord|Extra 100 / Long|L",
  "Lord|Blue 100 / Long|L",
  "Denim|Red|L, XL, 2XL, 3XL, 6XL",
  "Denim|Blue|L, XL, 2XL, 3XL",
  "Denim|Red Duo|6XL",
  "Burton|Red / Original|L, XL, 2XL, 3XL, 5XL",
  "Burton|Blue|L, XL, 2XL, 3XL",
  "Burton|Red Duo|5XL",
  "Elixyr|Red|L, XL, 2XL, 4XL, 5XL",
  "Elixyr|Blue|XL, 2XL",
  "Elixyr+|M-Type Green|L, XL, 2XL",
  "Elixyr+|X-Type Blue|XL, 2XL",
  "Paramount|Red|L, 2XL, 3XL, 5XL",
  "Paramount|Blue|L, 2XL, 3XL, 5XL",
  "Paramount|Silver|L, 2XL",
  "R1|Blue|L",
  "R1|Red|L",
  "R1|Minima / Slim|L",
  "Vogue|Bleue|L",
  "Vogue|Lilas|L",
  "Vogue|Caractère|L",
  "F6|Original|L, 2XL",
  "F6|Blue|L",
  "F6|Silver|L",
  "Fair Play|Red|L, XL",
  "Fair Play|Blue|L, XL",
  "American Spirit|Blue|L",
  "American Spirit|Yellow|L",
  "American Spirit|Orange / Organic|L",
  "Pueblo|Classic / Beige|L",
  "Pueblo|Blue|L",
  "Pueblo|Orange|L",
  "Ernte 23|Original|L",
  "R6|Red / Classic|L",
  "Reval|Filter|L",
  "Roth-Händle|Filter|L",
  "Dunhill|International Red|L",
  "Dunhill|Blue|L",
  "Benson & Hedges|Gold|L",
  "Gitanes|Blondes|L",
  "Pepe|Rich Green|L, 4XL",
  "Pepe|Bright Green|L, 4XL",
  "Manitou|Organic|L",
  "Mark Adams No. 1 / Mark1|Red|L, XL",
  "Mark Adams No. 1 / Mark1|Blue|L, XL",
  "Tawa|Red|XL, 2XL",
  "Tawa|Silver|XL",
  "Woodland|Craft / Wood Filter|L",
  "Las Vegas|Red|L, 2XL, 5XL",
  "Las Vegas|Blue|L, 2XL",
  "Ducal|Red|L, 2XL",
  "Ducal|Gold|L, 2XL",
  "Ducal|Silver|L, 2XL",
  "Fargo|Red|L, 5XL",
  "Esse|Red Superslim|L",
  "Esse|Blue Superslim|L",
  "Allure|Tabac Superslim|L, 4XL",
].flatMap((entry) => {
  const [brand, variant, sizes] = entry.split("|");
  return sizes.split(",").map((size) => `${brand} ${variant}, ${size.trim()}`);
});

window.DEFAULT_CATALOGS = {
  beverages: window.DEFAULT_ARTICLE_CATALOG,
  cigarettes: window.DEFAULT_CIGARETTE_CATALOG,
};

